// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Agentic data refresh route
// Generated by Hermes Agent (Nous Research)
//
// POST /api/refresh
// Tries data sources in priority order. Returns latest verified stats as JSON.
// Falls back to static data on any failure — never returns 5xx.
// Primary LLM: Google Gemini 1.5 Flash (7 keys, multi-key fallback).
// ─────────────────────────────────────────────────────────────────────────────

import { LIVE_STATS } from "@/data/floodData";
import type { LiveStats } from "@/types/flood";

// ── OpenAI-compatible client for free LLM alternatives ────────────────────────
function createOpenAIClient(baseURL: string, apiKey: string) {
  return {
    async chat(messages: Array<{ role: string; content: string }>) {
      const res = await fetch(`${baseURL}/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "auto",
          messages,
          max_tokens: 1000,
          temperature: 0.1,
          response_format: { type: "json_object" },
        }),
        signal: AbortSignal.timeout(15000),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      return data.choices?.[0]?.message?.content ?? "";
    },
  };
}

// ── Source 1: BIPAD Nepal Govt API (highest authority, no key needed) ─────────
async function fetchBIPAD(): Promise<Partial<LiveStats> | null> {
  try {
    const res = await fetch(
      "https://bipadportal.gov.np/api/v1/incident/?format=json&page_size=20",
      { signal: AbortSignal.timeout(7000) }
    );
    if (!res.ok) return null;
    const data = await res.json();

    const incident = (data.results ?? []).find((r: Record<string, unknown>) =>
      String(r.title ?? "").toLowerCase().includes("bhote") ||
      String(r.title ?? "").toLowerCase().includes("flood") ||
      String(r.date ?? "").startsWith("2026-08-26")
    );
    if (!incident) return null;

    return {
      deaths_nepal: (incident.death as number) ?? null,
      missing_nepal: (incident.missing as number) ?? null,
      rescued: (incident.rescued as number) ?? null,
      source: "BIPAD Nepal Government Portal",
      last_updated: (incident.updated_at as string) ?? new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

// ── Source 2: UN OCHA ReliefWeb (no key needed) ────────────────────────────────
async function fetchReliefWeb(): Promise<Partial<LiveStats> | null> {
  try {
    const url =
      "https://api.reliefweb.int/v1/reports?" +
      "appname=nepal-flood-map&" +
      "filter[conditions][0][field]=country.iso3&filter[conditions][0][value]=NPL&" +
      "filter[conditions][1][field]=date.created&filter[conditions][1][value][from]=2026-08-26&" +
      "sort[]=date.created:desc&limit=3&fields[include][]=title&fields[include][]=date";
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return null;
    const data = await res.json();
    const latest = data.data?.[0];
    if (!latest) return null;
    return {
      source: `ReliefWeb/OCHA: ${latest.fields?.title ?? "Nepal SITREP"}`,
      last_updated: latest.fields?.date?.created ?? new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

// ── Source 3: Free RSS News Aggregator (no API key needed) ────────────────────
async function fetchViaRSS(): Promise<Partial<LiveStats> | null> {
  try {
    const res = await fetch("/api/rss-aggregate", {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return null;
    const data = await res.json();
    if (!data.deaths_total) return null;
    return data;
  } catch {
    return null;
  }
}

// ── Source 4: Free LLM Alternatives ────────────────────────────────────────────
async function fetchViaFreeLLM(): Promise<Partial<LiveStats> | null> {
  const providers = [
    {
      name: "NVIDIA NIM",
      baseURL: process.env.NVIDIA_NIM_BASE_URL || "https://integrate.api.nvidia.com/v1",
      apiKey: process.env.NVIDIA_API_KEY,
    },
    {
      name: "Groq",
      baseURL: "https://api.groq.com/openai/v1",
      apiKey: process.env.GROQ_API_KEY,
    },
    {
      name: "Together AI",
      baseURL: "https://api.together.xyz/v1",
      apiKey: process.env.TOGETHER_API_KEY,
    },
    {
      name: "OpenRouter",
      baseURL: "https://openrouter.ai/api/v1",
      apiKey: process.env.OPENROUTER_API_KEY,
    },
  ];

  const systemPrompt =
    "You are a disaster data analyst monitoring the August 26 2026 Nepal glacial flood " +
    "(Bhote Koshi / Lhende Khola). Search for the LATEST confirmed official figures from " +
    "Nepal Police, Nepal Army, NDRRMA, or major wire services (AP, Reuters, ABC News, NBC News). " +
    "Ignore early estimates — use only the most recent confirmed figures. " +
    "Return ONLY valid JSON with these exact keys (all numbers must be numeric type): " +
    '{"deaths_nepal":number,"deaths_tibet":number,"deaths_total":number,' +
    '"missing_nepal":number,"missing_foreigners":number,"missing_americans":number,' +
    '"rescued":number,"impacted_total":number,"powerloss_mw":number,' +
    '"source":"URL","last_updated":"ISO8601"} ' +
    "No markdown. No explanation. JSON only.";

  for (const provider of providers) {
    if (!provider.apiKey) continue;
    try {
      const client = createOpenAIClient(provider.baseURL, provider.apiKey);
      const text = await client.chat([
        { role: "system", content: systemPrompt },
        { role: "user", content: "Get latest Nepal 2026 flood figures now." },
      ]);
      const clean = text.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(clean) as Partial<LiveStats>;
      if (typeof parsed.deaths_total === "number") {
        return { ...parsed, source: `${provider.name}: ${parsed.source ?? "LLM"}` };
      }
    } catch {
      continue;
    }
  }
  return null;
}

// ── Source 4.5: Google Gemini (multi-key fallback) ─────────────────────────────
async function fetchViaGemini(): Promise<Partial<LiveStats> | null> {
  const keys: string[] = [];
  for (let i = 1; i <= 7; i++) {
    const key = process.env[`GEMINI_API_KEY${i}`];
    if (key?.trim()) keys.push(key.trim());
  }
  if (keys.length === 0) return null;

  const exhaustedKeys = new Set<string>();

  function isGeminiRateLimited(status: number, body: unknown): boolean {
    if (status === 429) return true;
    if (status === 400 || status === 403) {
      if (body && typeof body === "object" && "error" in body) {
        const error = body.error as Record<string, unknown>;
        if (error && typeof error === "object") {
          if ("message" in error) {
            const msg = String(error.message).toLowerCase();
            if (msg.includes("quota") || msg.includes("limit") || msg.includes("exceeded") || msg.includes("rate")) {
              return true;
            }
          }
          if ("details" in error && Array.isArray(error.details)) {
            for (const detail of error.details as Array<Record<string, unknown>>) {
              if ("message" in detail) {
                const msg = String(detail.message).toLowerCase();
                if (msg.includes("quota") || msg.includes("limit") || msg.includes("exceeded") || msg.includes("rate")) {
                  return true;
                }
              }
            }
          }
        }
      }
    }
    return false;
  }

  const systemPrompt =
    "You are a disaster data analyst monitoring the August 26 2026 Nepal glacial flood " +
    "(Bhote Koshi / Lhende Khola). Search for the LATEST confirmed official figures from " +
    "Nepal Police, Nepal Army, NDRRMA, or major wire services (AP, Reuters, ABC News, NBC News). " +
    "Ignore early estimates — use only the most recent confirmed figures. " +
    "Return ONLY valid JSON with these exact keys (all numbers must be numeric type): " +
    '{"deaths_nepal":number,"deaths_tibet":number,"deaths_total":number,' +
    '"missing_nepal":number,"missing_foreigners":number,"missing_americans":number,' +
    '"rescued":number,"impacted_total":number,"powerloss_mw":number,' +
    '"source":"URL","last_updated":"ISO8601"} ' +
    "No markdown. No explanation. JSON only.";

  for (const key of keys) {
    if (exhaustedKeys.has(key)) continue;

    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${key}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              { role: "user", parts: [{ text: systemPrompt }] },
              { role: "user", parts: [{ text: "Get latest Nepal 2026 flood figures now." }] },
            ],
            generationConfig: {
              temperature: 0.1,
              maxOutputTokens: 1000,
              responseMimeType: "application/json",
            },
          }),
          signal: AbortSignal.timeout(15000),
        }
      );

      if (res.ok) {
        const data = await res.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
        if (!text) {
          console.log(`[Gemini] Key ending in ${key.slice(-4)} returned empty response`);
          continue;
        }
        const clean = text.replace(/```json|```/g, "").trim();
        const parsed = JSON.parse(clean) as Partial<LiveStats>;
        if (typeof parsed.deaths_total === "number") {
          console.log(`[Gemini] Key ending in ${key.slice(-4)} succeeded`);
          return { ...parsed, source: `Gemini: ${parsed.source ?? "LLM"}` };
        }
        console.log(`[Gemini] Key ending in ${key.slice(-4)} returned non-numeric data`);
        continue;
      }

      const status = res.status;
      let body: unknown;
      try { body = await res.json(); } catch { body = null; }

      if (isGeminiRateLimited(status, body)) {
        exhaustedKeys.add(key);
        console.log(`[Gemini] Key ending in ${key.slice(-4)} rate-limited (${status})`);
        continue;
      }

      if (status === 404) {
        console.log(`[Gemini] Key ending in ${key.slice(-4)} has no model access (404)`);
        continue;
      }

      console.log(`[Gemini] Key ending in ${key.slice(-4)} failed: HTTP ${status}`);
    } catch (err) {
      console.log(`[Gemini] Key ending in ${key.slice(-4)} error: ${String(err)}`);
      continue;
    }
  }

  console.log(`[Gemini] All ${keys.length} keys exhausted`);
  return null;
}

// ── Strip null/undefined so static fallbacks aren't overwritten ────────────────
function cleanPartial<T extends Partial<Record<string, unknown>>>(obj: T | null): Partial<T> {
  if (!obj) return {};
  const result: Partial<T> = {};
  for (const key of Object.keys(obj)) {
    const val = obj[key];
    if (val !== null && val !== undefined) {
      (result as Record<string, unknown>)[key] = val;
    }
  }
  return result;
}

// ── Main handler ────────────────────────────────────────────────────────────────
export async function POST() {
  const [bipad, reliefweb, rss, freeLLM, gemini] = await Promise.allSettled([
    fetchBIPAD(),
    fetchReliefWeb(),
    fetchViaRSS(),
    fetchViaFreeLLM(),
    fetchViaGemini(),
  ]);

  const bipadData      = bipad.status     === "fulfilled" ? cleanPartial(bipad.value)      : null;
  const reliefwebData  = reliefweb.status === "fulfilled" ? cleanPartial(reliefweb.value)  : null;
  const rssData        = rss.status       === "fulfilled" ? cleanPartial(rss.value)        : null;
  const freeLLMData    = freeLLM.status   === "fulfilled" ? cleanPartial(freeLLM.value)    : null;
  const geminiData     = gemini.status    === "fulfilled" ? cleanPartial(gemini.value)     : null;

  const anyLive = bipadData ?? freeLLMData ?? rssData ?? geminiData ?? reliefwebData;

  const merged: LiveStats = {
    ...LIVE_STATS,
    ...(geminiData ?? {}),
    ...(freeLLMData ?? {}),
    ...(rssData ?? {}),
    ...(reliefwebData ?? {}),
    ...(bipadData ?? {}),
    fallback: !anyLive,
  };

  return Response.json(merged, { status: 200 });
}
