// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Agentic data refresh route
// Generated by Claude (Anthropic) — claude.ai
//
// POST /api/refresh
// Tries data sources in priority order. Returns latest verified stats as JSON.
// Falls back to static data on any failure — never returns 5xx.
// ─────────────────────────────────────────────────────────────────────────────

import Anthropic        from "@anthropic-ai/sdk";
import { LIVE_STATS }  from "@/data/floodData";
import type { LiveStats } from "@/types/flood";

const client = new Anthropic();

// ── Source 1: BIPAD Nepal Govt API (highest authority, no key needed) ─────────
async function fetchBIPAD(): Promise<Partial<LiveStats> | null> {
  try {
    const res = await fetch(
      "https://bipadportal.gov.np/api/v1/incident/?format=json&page_size=20",
      { signal: AbortSignal.timeout(7000) }
    );
    if (!res.ok) return null;
    const data = await res.json();

    const incident = (data.results ?? []).find((r: Record<string, unknown>) =>
      String(r.title ?? "").toLowerCase().includes("bhote") ||
      String(r.title ?? "").toLowerCase().includes("flood") ||
      String(r.date  ?? "").startsWith("2026-08-26")
    );
    if (!incident) return null;

    return {
      deaths_nepal:  (incident.death    as number) ?? null,
      missing_nepal: (incident.missing  as number) ?? null,
      rescued:       (incident.rescued  as number) ?? null,
      source:        "BIPAD Nepal Government Portal",
      last_updated:  (incident.updated_at as string) ?? new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

// ── Source 2: UN OCHA ReliefWeb (no key needed — just appname param) ──────────
async function fetchReliefWeb(): Promise<Partial<LiveStats> | null> {
  try {
    const url =
      "https://api.reliefweb.int/v1/reports?" +
      "appname=nepal-flood-map&" +
      "filter[conditions][0][field]=country.iso3&filter[conditions][0][value]=NPL&" +
      "filter[conditions][1][field]=date.created&filter[conditions][1][value][from]=2026-08-26&" +
      "sort[]=date.created:desc&limit=3&fields[include][]=title&fields[include][]=date";
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return null;
    const data = await res.json();
    const latest = data.data?.[0];
    if (!latest) return null;
    // ReliefWeb confirms there are active SITREPs — update timestamp only here
    return {
      source:       `ReliefWeb/OCHA: ${latest.fields?.title ?? "Nepal SITREP"}`,
      last_updated: latest.fields?.date?.created ?? new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

// ── Source 3: Anthropic web_search — reads live news ─────────────────────────
async function fetchViaAnthropic(): Promise<Partial<LiveStats> | null> {
  if (!process.env.ANTHROPIC_API_KEY) return null;
  try {
    const tools: Anthropic.ToolUnion[] = [{ type: "web_search_20250305", name: "web_search" } as Anthropic.WebSearchTool20250305];
    const response = await client.messages.create({
      model:      "claude-sonnet-4-6",
      max_tokens: 1000,
      tools:      tools,
      system:
        "You are a disaster data analyst monitoring the August 26 2026 Nepal glacial flood " +
        "(Bhote Koshi / Lhende Khola). Search for the LATEST confirmed official figures from " +
        "Nepal Police, Nepal Army, NDRRMA, or major wire services (AP, Reuters, ABC News, NBC News). " +
        "Ignore early estimates — use only the most recent confirmed figures. " +
        "Return ONLY valid JSON with these exact keys (all numbers must be numeric type): " +
        '{"deaths_nepal":number,"deaths_tibet":number,"deaths_total":number,' +
        '"missing_nepal":number,"missing_foreigners":number,"missing_americans":number,' +
        '"rescued":number,"impacted_total":number,"powerloss_mw":number,' +
        '"source":"URL","last_updated":"ISO8601"} ' +
        "No markdown. No explanation. JSON only.",
      messages: [{ role: "user", content: "Get latest Nepal 2026 flood figures now." }],
    });

    const text = response.content
      .filter((b) => b.type === "text")
      .map((b) => (b as { type: "text"; text: string }).text)
      .join("");
    const clean  = text.replace(/```json|```/g, "").trim();
    const parsed = JSON.parse(clean) as Partial<LiveStats>;
    if (typeof parsed.deaths_total !== "number") return null;
    return parsed;
  } catch {
    return null;
  }
}

// Remove null/undefined fields so they don't overwrite static fallback values
function cleanPartial<T extends Partial<Record<string, unknown>>>(obj: T | null): Partial<T> {
  if (!obj) return {};
  const result: Partial<T> = {};
  for (const key of Object.keys(obj)) {
    const val = obj[key];
    if (val !== null && val !== undefined) {
      (result as Record<string, unknown>)[key] = val;
    }
  }
  return result;
}

export async function POST() {
  // Run all sources concurrently with independent timeouts
  const [bipad, reliefweb, anthropic] = await Promise.allSettled([
    fetchBIPAD(),
    fetchReliefWeb(),
    fetchViaAnthropic(),
  ]);

  const bipadData     = bipad.status     === "fulfilled" ? cleanPartial(bipad.value)     : null;
  const reliefwebData = reliefweb.status === "fulfilled" ? cleanPartial(reliefweb.value) : null;
  const anthropicData = anthropic.status === "fulfilled" ? cleanPartial(anthropic.value) : null;

  const anyLive = bipadData ?? anthropicData ?? reliefwebData;

  // Merge: static base → Anthropic (news) → ReliefWeb (timestamp) → BIPAD (override)
  const merged: LiveStats = {
    ...LIVE_STATS,
    ...(anthropicData ?? {}),
    ...(reliefwebData ?? {}),
    ...(bipadData     ?? {}),
    fallback: !anyLive,
  };

  return Response.json(merged, { status: 200 });
}
