// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — GDACS RSS poller
// Generated by Hermes Agent (Nous Research)
//
// Polls UN's Global Disaster Alert feed every 5 minutes.
// Critical right now: detects the Tibet barrier lake secondary event before news breaks.
// ─────────────────────────────────────────────────────────────────────────────

import type { GDACSAlert } from "@/types/flood";

export async function checkGDACS(): Promise<GDACSAlert> {
  try {
    const res = await fetch("https://www.gdacs.org/xml/rss.xml", {
      signal: AbortSignal.timeout(5000),
      next:   { revalidate: 300 }, // Next.js ISR cache — revalidate every 5 min
    });
    if (!res.ok) return { alertLevel: null, title: null, link: null };

    const text = await res.text();

    // Find <item> blocks mentioning Nepal
    const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
    const items     = [...text.matchAll(itemRegex)].map((m) => m[1]);
    const nepalItem = items.find((i) => /nepal|bhote|trishuli/i.test(i));

    if (!nepalItem) return { alertLevel: null, title: null, link: null };

    const title = nepalItem.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/)?.[1]
               ?? nepalItem.match(/<title>(.*?)<\/title>/)?.[1]
               ?? null;
    const link  = nepalItem.match(/<link>(.*?)<\/link>/)?.[1] ?? null;

    // GDACS encodes alert level in gdacs:alertlevel or severity field
    const rawLevel = (
      nepalItem.match(/gdacs:alertlevel>(.*?)</i)?.[1] ??
      nepalItem.match(/alertlevel.*?['"](green|orange|red)['"]/i)?.[1] ??
      ""
    ).toLowerCase();

    const alertLevel =
      rawLevel === "red"    ? "red"    :
      rawLevel === "orange" ? "orange" :
      rawLevel === "green"  ? "green"  : null;

    return { alertLevel, title, link };
  } catch {
    return { alertLevel: null, title: null, link: null };
  }
}
