// =============================================================================
// Nepal Flood Map — AlertBanner.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Full-width alert banner: active emergency, critical alerts non-dismissible
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
