// =============================================================================
// Nepal Flood Map — CoordinateTable.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Coordinate table: sort, district filter, copy lat/lng, CSV export
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
