// =============================================================================
// Nepal Flood Map — route.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// GET /api/cron: Vercel cron trigger, fires /api/refresh every 10 minutes
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
