// =============================================================================
// Nepal Flood Map — dataSources.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Agentic data source registry: all external APIs in priority order
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
