// =============================================================================
// Nepal Flood Map — flood.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// TypeScript types: FloodOrigin, FloodLocation, LiveStats, AlertLevel, GDACSAlert
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
