// =============================================================================
// Nepal Flood Map — floodData.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Static verified data: coordinates, LIVE_STATS, TIMELINE_EVENTS, ACTIVE_ALERTS (Aug 29 2026)
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
