// =============================================================================
// Nepal Flood Map — FloodMap.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Interactive map: Mapbox GL JS animated flow path + Leaflet/OSM fallback (no token needed)
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
