// =============================================================================
// Nepal Flood Map — FloodTimeline.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Event timeline: staggered CSS animation, ONGOING indicator, jump-to-latest button
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
