// =============================================================================
// Nepal Flood Map — gdacs.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// GDACS RSS poller: UN real-time disaster alert feed (Tibet barrier lake detection)
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
