// =============================================================================
// Nepal Flood Map — layout.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Root layout: metadata, dark mode, OpenGraph tags
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
