// =============================================================================
// Nepal Flood Map — LiveDashboard.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Live stats dashboard: auto-refresh 60s, GDACS alerts, Recharts nationality bar chart
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
