// =============================================================================
// Nepal Flood Map — page.tsx
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// Root page: AlertBanner + header + map/dashboard grid + timeline + table + footer
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
