// =============================================================================
// Nepal Flood Map — route.ts
// Generated by Claude (Anthropic) — claude.ai
// Aug 29 2026 · Bhote Koshi / Lhende Khola flood event
//
// POST /api/refresh: multi-source pipeline: BIPAD -> ReliefWeb -> Anthropic -> static fallback
//
// Full implementation: see HERMES_AGENT_PROMPT.md
// =============================================================================
