// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Field Guide Infographic Page (Route: /field-guide)
// Generated by Hermes Agent (Nous Research)
//
// Infographic-style visual guide for field workers — large numbers,
// color-coded sections, step-by-step flow, minimal text density.
// ─────────────────────────────────────────────────────────────────────────────

import type { ReactNode } from "react";
import Link from "next/link";

// ── Color Tokens ──────────────────────────────────────────────────────────────
const C = {
  bg:         "#0a0f1e",
  card:       "#141b2d",
  border:     "#1e2a45",
  text:       "#f1f5f9",
  muted:      "#7e8ba3",
  red:        "#ef4444",
  redBg:      "rgba(239,68,68,0.12)",
  orange:     "#f97316",
  orangeBg:   "rgba(249,115,22,0.12)",
  yellow:     "#eab308",
  yellowBg:   "rgba(234,179,8,0.12)",
  blue:       "#3b82f6",
  blueBg:     "rgba(59,130,246,0.12)",
  green:      "#22c55e",
  greenBg:    "rgba(34,197,94,0.12)",
  purple:     "#a855f7",
  purpleBg:   "rgba(168,85,247,0.12)",
  divider:    "#1e2a45",
};

// ── Icon Shapes (inline SVG, no external deps) ────────────────────────────────
const Icon: Record<string, React.ReactElement> = {
  marker: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <defs><radialGradient id="mg" cx="50%" cy="50%" r="50%">
        <stop offset="60%" stop-color="#ef4444"/><stop offset="100%" stop-color="#dc2626"/>
      </radialGradient></defs>
      <circle cx="14" cy="10" r="6" fill="url(#mg)"/>
      <circle cx="14" cy="10" r="10" fill="none" stroke="#ef4444" strokeWidth="2" opacity="0.35"/>
      <circle cx="14" cy="10" r="14" fill="none" stroke="#ef4444" strokeWidth="1.5" opacity="0.15"/>
      <rect x="8" y="24" width="12" height="2.5" rx="1.25" fill="#1e2a45"/>
      <rect x="10" y="26" width="8" height="2" rx="1" fill="#1e2a45"/>
    </svg>
  ),
  dashboard: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="2" y="4" width="24" height="17" rx="3" stroke="#3b82f6" strokeWidth="1.8"/>
      <rect x="5" y="7" width="7" height="3" rx="1" fill="#3b82f6"/>
      <rect x="14" y="7" width="7" height="3" rx="1" fill="#3b82f6"/>
      <rect x="5" y="12" width="7" height="2" rx="1" fill="#3b82f6" opacity="0.5"/>
      <rect x="14" y="12" width="7" height="2" rx="1" fill="#3b82f6" opacity="0.5"/>
      <rect x="5" y="16" width="7" height="2" rx="1" fill="#3b82f6" opacity="0.3"/>
      <rect x="14" y="16" width="7" height="2" rx="1" fill="#3b82f6" opacity="0.3"/>
    </svg>
  ),
  news: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="2" y="4" width="24" height="20" rx="3" stroke="#a855f7" strokeWidth="1.8"/>
      <path d="M14 7 L14 19 M8 12 L14 7 L20 12" stroke="#a855f7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
      <circle cx="14" cy="7" r="1.5" fill="#a855f7"/>
    </svg>
  ),
  river: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <path d="M2 14 Q6 8 11 14 Q16 20 21 14 Q24 10 26 14" stroke="#22c55e" strokeWidth="2.2" strokeLinecap="round" fill="none"/>
      <circle cx="11" cy="14" r="2.2" fill="#22c55e"/>
      <circle cx="16" cy="14" r="1.8" fill="#22c55e" opacity="0.6"/>
      <circle cx="21" cy="14" r="1.4" fill="#22c55e" opacity="0.3"/>
    </svg>
  ),
  satellite: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <circle cx="10" cy="10" r="7.5" stroke="#eab308" strokeWidth="1.8"/>
      <circle cx="10" cy="10" r="4" fill="#eab308" opacity="0.2"/>
      <circle cx="10" cy="10" r="1.5" fill="#eab308"/>
      <rect x="16" y="10" width="10" height="3" rx="1.5" fill="#3b82f6" opacity="0.6"/>
      <rect x="20" y="5" width="2" height="10" rx="1" fill="#3b82f6" opacity="0.4"/>
      <circle cx="21" cy="11.5" r="1.2" fill="#3b82f6"/>
    </svg>
  ),
  export: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="3" y="3" width="7.5" height="10" rx="1.5" stroke="#b45309" strokeWidth="1.8"/>
      <rect x="3" y="17" width="7.5" height="8" rx="1.5" stroke="#b45309" strokeWidth="1.8"/>
      <rect x="11" y="3" width="7.5" height="7" rx="1.5" stroke="#b45309" strokeWidth="1.8"/>
      <rect x="18.5" y="3" width="7.5" height="7" rx="1.5" stroke="#b45309" strokeWidth="1.8"/>
      <rect x="11" y="12.5" width="14.5" height="13" rx="1.5" stroke="#b45309" strokeWidth="1.8"/>
    </svg>
  ),
  phone: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="6.5" y="3" width="15" height="22" rx="3" stroke="#22c55e" strokeWidth="1.8"/>
      <rect x="10" y="20" width="8" height="5" rx="1" fill="#22c55e" opacity="0.5"/>
      <path d="M14 9 L14 15" stroke="#22c55e" strokeWidth="2" strokeLinecap="round"/>
      <path d="M10 11.5 L14 15 L18 11.5" stroke="#22c55e" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
    </svg>
  ),
  gps: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <circle cx="14" cy="14" r="10" stroke="#b45309" strokeWidth="1.8"/>
      <circle cx="14" cy="14" r="4" fill="#b45309" opacity="0.3"/>
      <circle cx="14" cy="14" r="1.5" fill="#b45309"/>
      <line x1="14" y1="2" x2="14" y2="6" stroke="#b45309" strokeWidth="1.5"/>
      <line x1="14" y1="22" x2="14" y2="26" stroke="#b45309" strokeWidth="1.5"/>
      <line x1="2" y1="14" x2="6" y2="14" stroke="#b45309" strokeWidth="1.5"/>
      <line x1="22" y1="14" x2="26" y2="14" stroke="#b45309" strokeWidth="1.5"/>
    </svg>
  ),
  qgis: (
    <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
      <rect x="2" y="4" width="24" height="19" rx="2" stroke="#ef4444" strokeWidth="1.8"/>
      <rect x="4" y="6" width="12" height="3" rx="1" fill="#ef4444" opacity="0.7"/>
      <rect x="4" y="11" width="18" height="3" rx="1" fill="#ef4444" opacity="0.5"/>
      <rect x="4" y="16" width="8" height="3" rx="1" fill="#ef4444" opacity="0.4"/>
      <circle cx="18" cy="10" r="2" fill="#22c55e" opacity="0.6"/>
      <circle cx="20" cy="13" r="1.5" fill="#3b82f6" opacity="0.6"/>
    </svg>
  ),
  arrow: (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M5 12 L19 12 M15 7 L19 12 L15 17" stroke="#7e8ba3" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
  check: (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
      <circle cx="10" cy="10" r="9" stroke="#22c55e" strokeWidth="1.6"/>
      <path d="M6 10 L9 13 L14 7" stroke="#22c55e" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
  warning: (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
      <path d="M10 1.5 L18.5 16.5 H1.5 Z" stroke="#f97316" strokeWidth="1.8" strokeLinejoin="round"/>
      <line x1="10" y1="9" x2="10" y2="12" stroke="#f97316" strokeWidth="2" strokeLinecap="round"/>
      <circle cx="10" cy="15" r="1.2" fill="#f97316"/>
    </svg>
  ),
  wifi: (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
      <path d="M10 2 L10 5 M10 5 L6 9 M10 5 L14 9" stroke="#22c55e" strokeWidth="1.8" strokeLinecap="round"/>
      <path d="M10 8 L10 11 M10 11 L6.5 14.5 M10 11 L13.5 14.5" stroke="#22c55e" strokeWidth="1.4" strokeLinecap="round" opacity="0.7"/>
    </svg>
  ),
};

// ── Section Card ──────────────────────────────────────────────────────────────
function SectionCard({
  icon,
  title,
  children,
  accent,
  bg,
  border,
}: {
  icon: ReactNode;
  title: string;
  children: ReactNode;
  accent?: string;
  bg?: string;
  border?: string;
}) {
  return (
    <section
      style={{
        background: bg ?? C.card,
        border: `1px solid ${border ?? C.border}`,
        borderRadius: "16px",
        padding: "28px",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* Accent top stripe */}
      {accent && (
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            height: "4px",
            background: accent,
          }}
        />
      )}
      <div
        style={{
          marginBottom: "18px",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "14px",
          }}
        >
          <div style={{ color: accent ?? "#fff" }}>{icon}</div>
          <h2
            style={{
              fontFamily: "Inter, system-ui, sans-serif",
              fontSize: "20px",
              fontWeight: 700,
              color: C.text,
              margin: 0,
              letterSpacing: "-0.01em",
            }}
          >
            {title}
          </h2>
        </div>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
        {children}
      </div>
    </section>
  );
}

// ── Step Item ────────────────────────────────────────────────────────────────
function Step({
  n,
  text,
  sub,
}: {
  n: number;
  text: string;
  sub?: string;
}) {
  return (
    <div style={{ display: "flex", gap: "16px", alignItems: "flex-start" }}>
      <div
        style={{
          flexShrink: 0,
          width: "34px",
          height: "34px",
          borderRadius: "50%",
          background: C.redBg,
          border: `2px solid ${C.red}`,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: C.red,
          fontFamily: "Inter, system-ui, sans-serif",
          fontWeight: 800,
          fontSize: "16px",
        }}
      >
        {n}
      </div>
      <div style={{ flex: 1 }}>
        <div
          style={{
            fontFamily: "Inter, system-ui, sans-serif",
            fontSize: "15px",
            fontWeight: 600,
            color: C.text,
            margin: 0,
          }}
        >
          {text}
        </div>
        {sub && (
          <div
            style={{
              fontFamily: "Inter, system-ui, sans-serif",
              fontSize: "13px",
              color: C.muted,
              marginTop: "2px",
            }}
          >
            {sub}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Stat Block ────────────────────────────────────────────────────────────────
function Stat({
  label,
  value,
  color,
  bg,
}: {
  label: string;
  value: string | number;
  color?: string;
  bg?: string;
}) {
  return (
    <div
      style={{
        background: bg ?? C.bg,
        border: "1px solid C.border",
        borderRadius: "12px",
        padding: "16px 14px",
        textAlign: "center",
      }}
    >
      <div
        style={{
          fontFamily: "Inter, system-ui, sans-serif",
          fontSize: "30px",
          fontWeight: 800,
          color: color ?? C.text,
          lineHeight: 1.1,
        }}
      >
        {value}
      </div>
      <div
        style={{
          fontFamily: "Inter, system-ui, sans-serif",
          fontSize: "11px",
          color: C.muted,
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          marginTop: "4px",
        }}
      >
        {label}
      </div>
    </div>
  );
}

// ── Tag (pill) ────────────────────────────────────────────────────────────────
function Tag({ label, color }: { label: string; color: string }) {
  return (
    <span
      style={{
        display: "inline-block",
        padding: "4px 10px",
        borderRadius: "999px",
        background: `${color}22`,
        color,
        fontFamily: "Inter, system-ui, sans-serif",
        fontSize: "11px",
        fontWeight: 600,
        letterSpacing: "0.03em",
      }}
    >
      {label}
    </span>
  );
}

// ── Reliability Bar ───────────────────────────────────────────────────────────
function ReliBar({ stars }: { stars: number }) {
  return (
    <div style={{ display: "flex", gap: "2px", alignItems: "center" }}>
      {Array.from({ length: 5 }, (_, i) => (
        <div
          key={i}
          style={{
            width: "8px",
            height: "14px",
            borderRadius: "2px",
            background: i < stars ? "#facc15" : "#1e2a45",
            transition: "background 0.2s",
          }}
        />
      ))}
    </div>
  );
}

// ── Mini grid ────────────────────────────────────────────────────────────────
function Grid2({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
        gap: "12px",
      }}
    >
      {children}
    </div>
  );
}

// ── Mini table (2-col key/value, infographic style) ──────────────────────────
function MiniRow({ label, value, valueColor }: { label: string; value?: string | null; valueColor?: string }) {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "8px 0",
        borderBottom: "1px solid C.divider",
        gap: "12px",
      }}
    >
      <div style={{ fontSize: "13px", color: C.muted, flex: 1 }}>{label}</div>
      {value && (
        <div
          style={{
            fontSize: "13px",
            fontWeight: 600,
            color: valueColor ?? C.text,
            textAlign: "right",
            whiteSpace: "nowrap",
          }}
        >
          {value}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGE
// ─────────────────────────────────────────────────────────────────────────────
export default function FieldGuidePage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: C.bg,
        fontFamily: "Inter, system-ui, -apple-system, sans-serif",
        color: C.text,
        padding: "20px 16px 40px",
      }}
    >
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <header
        style={{
          maxWidth: "820px",
          margin: "0 auto 24px",
          padding: "20px 0 0",
          borderTop: `2px solid ${C.red}`,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "12px" }}>
          <div style={{ color: C.red }}>
            <svg width="36" height="36" viewBox="0 0 36 36">
              <circle cx="18" cy="14" r="7" fill="#ef4444"/>
              <path d="M8 22 Q13 17 18 18 Q23 17 28 22 Q28 26 18 27 Q8 26 8 22Z" fill="#3b82f6"/>
            </svg>
          </div>
          <div>
            <h1
              style={{
                fontFamily: "Inter, system-ui, sans-serif",
                fontSize: "24px",
                fontWeight: 800,
                color: C.text,
                margin: 0,
                letterSpacing: "-0.02em",
              }}
            >
              Field Worker Guide
            </h1>
            <div
              style={{
                fontFamily: "Inter, system-ui, sans-serif",
                fontSize: "13px",
                color: C.muted,
                marginTop: "2px",
              }}
            >
              Nepal Army · Nepal Police · Armed Police Force · NDRRMA · Humanitarian Workers
            </div>
          </div>
        </div>

        {/* Stats row */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: "8px",
            background: C.card,
            borderRadius: "14px",
            padding: "16px 14px",
            border: "1px solid C.border",
            marginTop: "4px",
          }}
        >
          <Stat label="Deaths" value={584} color={C.red} />
          <Stat label="Missing" value={2600} color={C.orange} />
          <Stat label="Rescued" value={3000} color={C.green} />
          <Stat label="Bridges Lost" value={19} color={C.purple} />
        </div>
      </header>

      {/* ── Main Grid ───────────────────────────────────────────────────── */}
      <div
        style={{
          maxWidth: "820px",
          margin: "0 auto",
          display: "flex",
          flexDirection: "column",
          gap: "18px",
        }}
      >

        {/* Section 1: Quick Start */}
        <SectionCard
          icon={Icon.phone}
          title="Quick Start (2 minutes)"
          accent={C.blue}
        >
          <Step n={1} text="Open dashboard URL on your mobile browser" sub="Chrome or Safari" />
          <Step n={2} text="Add to Home Screen" sub="Works like an app — works offline" />
          <Step n={3} text="Map shows flood origin, affected locations & flow path" />
          <Step n={4} text="Tap any marker for details" sub="Coordinates · time hit · casualty info" />
          <div style={{ marginTop: "6px" }}>
            <Tag label="Install: Android Chrome → Menu → Add to HS" color={C.blue} />
            <span style={{ margin: "0 6px", color: C.muted }}>·</span>
            <Tag label="iOS Safari → Share → Add to HS" color={C.blue} />
          </div>
        </SectionCard>

        {/* Section 2: Legend — Visual decoding */}
        <SectionCard
          icon={Icon.marker}
          title="🗺️ Map Legend — What You See"
          accent={C.red}
        >
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "10px", marginBottom: "6px" }}>
            {/* Critical */}
            <div style={{ background: C.redBg, borderRadius: "10px", padding: "10px", textAlign: "center", border: `1px solid ${C.red}33` }}>
              <div style={{ color: C.red, fontSize: "22px", marginBottom: "4px" }}>🔴</div>
              <div style={{ fontSize: "12px", fontWeight: 700, color: C.red }}>CRITICAL</div>
              <div style={{ fontSize: "11px", color: C.muted, marginTop: "2px" }}>Rasuwagadhi · Timure · Syapru Besi</div>
            </div>
            {/* High */}
            <div style={{ background: C.orangeBg, borderRadius: "10px", padding: "10px", textAlign: "center", border: `1px solid ${C.orange}33` }}>
              <div style={{ color: C.orange, fontSize: "22px", marginBottom: "4px" }}>🟠</div>
              <div style={{ fontSize: "12px", fontWeight: 700, color: C.orange }}>HIGH</div>
              <div style={{ fontSize: "11px", color: C.muted, marginTop: "2px" }}>Dhunche · Trishuli Bazar · Nuwakot</div>
            </div>
            {/* Medium */}
            <div style={{ background: C.yellowBg, borderRadius: "10px", padding: "10px", textAlign: "center", border: `1px solid ${C.yellow}33` }}>
              <div style={{ color: C.yellow, fontSize: "22px", marginBottom: "4px" }}>🟡</div>
              <div style={{ fontSize: "12px", fontWeight: 700, color: C.yellow }}>MEDIUM</div>
              <div style={{ fontSize: "11px", color: C.muted, marginTop: "2px" }}>Devighat · Chitwan</div>
            </div>
          </div>
          <div style={{ display: "flex", gap: "10px", flexWrap: "wrap", alignItems: "center", fontSize: "13px", color: C.muted }}>
            <span>● Red line = flood flow path (southward)</span>
            <span>● White dot = glacier collapse origin</span>
          </div>
        </SectionCard>

        {/* Section 3: Dashboard */}
        <SectionCard
          icon={Icon.dashboard}
          title="📊 Live Dashboard"
          accent={C.blue}
        >
          <MiniRow label="Deaths / Missing / Rescued" value="Auto-refreshes every 60s" valueColor={C.green} />
          <MiniRow label="GDACS Alerts" value="UN secondary event detection" valueColor={C.orange} />
          <MiniRow label="Missing by nationality" value="Bar chart" />
          <MiniRow label="Active alerts" value="🔒 Critical = cannot dismiss" valueColor={C.red} />
        </SectionCard>

        {/* Section 4: River Gauge */}
        <SectionCard
          icon={Icon.river}
          title="🌊 River Gauge Data"
          accent={C.green}
        >
          <MiniRow label="Bahrabise" value="Bhote Koshi — ↑ Rising" valueColor={C.orange} />
          <MiniRow label="Benighat" value="Trishuli — ↓ Falling" valueColor={C.green} />
          <MiniRow label="Narayanghat" value="Narayani — → Steady" valueColor={C.muted} />
          <div style={{ marginTop: "2px" }}>
            <Tag label="Source: DHM Nepal — dhm.gov.np" color={C.green} />
            <span style={{ margin: "0 6px", color: C.muted }}>·</span>
            <Tag label="Lag: 3–6 hrs" color={C.muted} />
          </div>
        </SectionCard>

        {/* Section 5: News */}
        <SectionCard
          icon={Icon.news}
          title="📰 Live News Feed"
          accent={C.purple}
        >
          <MiniRow label="Sources" value="ABC · NBC · CBS · The Watchers · EarthSky" />
          <MiniRow label="API keys" value="None needed — free RSS" valueColor={C.green} />
          <MiniRow label="Action" value="Tap headline → full article" />
          <div style={{ marginTop: "2px" }}>
            <Tag label="Free — no API key required" color={C.purple} />
          </div>
        </SectionCard>

        {/* Section 6: Satellite */}
        <SectionCard
          icon={Icon.satellite}
          title="🛰️ Satellite Comparison"
          accent={C.yellow}
        >
          <MiniRow label="Pre-flood" value="Aug 20, 2026 — Sentinel-2" valueColor={C.muted} />
          <MiniRow label="Post-flood" value="Aug 28, 2026 — Sentinel-2" valueColor={C.red} />
          <div style={{ marginTop: "8px", display: "flex", gap: "8px", alignItems: "center" }}>
            <div style={{ flex: 1, background: "#1e2a45", borderRadius: "8px", height: "40px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "12px", color: C.muted }}>
              AUG 20
            </div>
            <div style={{ color: C.yellow, fontSize: "20px", flexShrink: 0 }}>↔</div>
            <div style={{ flex: 1, background: C.redBg, borderRadius: "8px", height: "40px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "12px", color: C.red, fontWeight: 600 }}>
              AUG 28
            </div>
          </div>
          <div style={{ marginTop: "8px" }}>
            <Tag label="Drag slider to compare" color={C.yellow} />
          </div>
        </SectionCard>

        {/* Section 7: Export */}
        <SectionCard
          icon={Icon.export}
          title="📥 Export Data"
          accent={C.orange}
        >
          <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "10px" }}>
            <div style={{ background: "linear-gradient(135deg, rgba(180,83,9,0.15), rgba(180,83,9,0.05))", borderRadius: "10px", padding: "12px", border: `1px solid ${C.orange}22` }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                <div style={{ color: C.orange, fontSize: "18px" }}>📄</div>
                <div style={{ fontSize: "13px", fontWeight: 700, color: C.text }}>GeoJSON</div>
              </div>
              <div style={{ fontSize: "11px", color: C.muted }}>QGIS · ArcGIS — Layer → Add Vector Layer</div>
            </div>
            <div style={{ background: "linear-gradient(135deg, rgba(59,130,246,0.15), rgba(59,130,246,0.05))", borderRadius: "10px", padding: "12px", border: `1px solid ${C.blue}22` }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                <div style={{ color: C.blue, fontSize: "18px" }}>🌍</div>
                <div style={{ fontSize: "13px", fontWeight: 700, color: C.text }}>KML</div>
              </div>
              <div style={{ fontSize: "11px", color: C.muted }}>Google Earth — File → Open → .kml</div>
            </div>
            <div style={{ background: "linear-gradient(135deg, rgba(34,197,94,0.15), rgba(34,197,94,0.05))", borderRadius: "10px", padding: "12px", border: `1px solid ${C.green}22` }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                <div style={{ color: C.green, fontSize: "18px" }}>📊</div>
                <div style={{ fontSize: "13px", fontWeight: 700, color: C.text }}>CSV</div>
              </div>
              <div style={{ fontSize: "11px", color: C.muted }}>Spreadsheet · database import</div>
            </div>
            <div style={{ background: "linear-gradient(135deg, rgba(168,85,247,0.15), rgba(168,85,247,0.05))", borderRadius: "10px", padding: "12px", border: `1px solid ${C.purple}22` }}>
              <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                <div style={{ color: C.purple, fontSize: "18px" }}>📋</div>
                <div style={{ fontSize: "13px", fontWeight: 700, color: C.text }}>PDF Report</div>
              </div>
              <div style={{ fontSize: "11px", color: C.muted }}>Print for coordination meetings</div>
            </div>
          </div>
        </SectionCard>

        {/* Section 8: Coordinate workflows */}
        <SectionCard
          icon={Icon.gps}
          title="📍 Using Coordinates in the Field"
          accent={C.orange}
        >
          {/* Copy */}
          <div style={{ marginBottom: "14px" }}>
            <div style={{ fontSize: "13px", fontWeight: 700, color: C.orange, marginBottom: "8px" }}>① Copy Coordinates</div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.orange, fontWeight: 800, fontSize: "15px" }}>1</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>
                Open <strong>Coordinate Table</strong> (bottom of page) → tap <strong>Copy</strong> next to any location
              </div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.orange, fontWeight: 800, fontSize: "15px" }}>2</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>
                Pastes as <code>lat,lng</code> — e.g. <code>28.2776,85.3776</code>
              </div>
            </div>
          </div>

          {/* GPS */}
          <div style={{ marginBottom: "14px" }}>
            <div style={{ fontSize: "13px", fontWeight: 700, color: C.orange, marginBottom: "8px" }}>② GPS / Garmin</div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.orange, fontWeight: 800, fontSize: "15px" }}>1</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Open GPS app → Navigate to Coordinates</div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.orange, fontWeight: 800, fontSize: "15px" }}>2</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Paste <code>28.2776,85.3776</code></div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.orange, fontWeight: 800, fontSize: "15px" }}>3</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Save as waypoint</div>
            </div>
          </div>

          {/* QGIS */}
          <div style={{ marginBottom: "14px" }}>
            <div style={{ fontSize: "13px", fontWeight: 700, color: C.purple, marginBottom: "8px" }}>③ QGIS</div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.purple, fontWeight: 800, fontSize: "15px" }}>1</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Export <strong>GeoJSON</strong> from dashboard</div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.purple, fontWeight: 800, fontSize: "15px" }}>2</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>QGIS → Layer → Add Layer → Add Vector Layer</div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.purple, fontWeight: 800, fontSize: "15px" }}>3</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Select downloaded <code>.geojson</code> → style by severity</div>
            </div>
          </div>

          {/* Google Earth */}
          <div>
            <div style={{ fontSize: "13px", fontWeight: 700, color: C.blue, marginBottom: "8px" }}>④ Google Earth</div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.blue, fontWeight: 800, fontSize: "15px" }}>1</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Export <strong>KML</strong> from dashboard</div>
            </div>
            <div style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginTop: "6px" }}>
              <div style={{ flexShrink: 0, width: "22px", color: C.blue, fontWeight: 800, fontSize: "15px" }}>2</div>
              <div style={{ flex: 1, fontSize: "13px", color: C.text }}>Google Earth → File → Open → select <code>.kml</code></div>
            </div>
          </div>
        </SectionCard>

        {/* Section 9: Data Reliability */}
        <SectionCard
          icon={Icon.check}
          title="📡 Data Sources & Reliability"
          accent={C.green}
        >
          <div style={{ display: "flex", flexDirection: "column", gap: "0" }}>
            <MiniRow label="Nepal Police" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>Nepal Police</div>
              <ReliBar stars={5} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>2–6 hrs</span>
            </div>
            <MiniRow label="BIPAD (Nepal Govt)" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>BIPAD Portal</div>
              <ReliBar stars={5} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>2–6 hrs</span>
            </div>
            <MiniRow label="NDRRMA" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>NDRRMA</div>
              <ReliBar stars={5} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>Daily</span>
            </div>
            <MiniRow label="ReliefWeb (UN OCHA)" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>UN OCHA</div>
              <ReliBar stars={4} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>Hourly</span>
            </div>
            <MiniRow label="GDACS (UN/JRC)" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>GDACS</div>
              <ReliBar stars={4} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>15 min</span>
            </div>
            <MiniRow label="USGS" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>USGS</div>
              <ReliBar stars={5} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>Real-time</span>
            </div>
            <MiniRow label="DHM Nepal" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>DHM</div>
              <ReliBar stars={4} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>3–6 hrs</span>
            </div>
            <MiniRow label="RSS News" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>RSS Feeds</div>
              <ReliBar stars={3} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>Real-time</span>
            </div>
            <MiniRow label="Static Fallback" value={null} />
            <div style={{ display: "flex", gap: "10px", alignItems: "center", padding: "6px 0 2px" }}>
              <div style={{ flex: 1, fontSize: "13px", color: C.muted }}>Verified Aug 29</div>
              <ReliBar stars={4} />
              <span style={{ fontSize: "11px", color: C.muted, marginLeft: "8px" }}>Fixed</span>
            </div>
          </div>
          <div style={{ marginTop: "12px", padding: "10px 14px", background: C.redBg, borderRadius: "10px", border: `1px solid ${C.red}22` }}>
            <div style={{ display: "flex", gap: "8px", alignItems: "center", fontSize: "13px", color: C.red }}>
              {Icon.warning}
              <div>
                <strong>All figures are provisional.</strong> Nepal Police / BIPAD are highest authority.
              </div>
            </div>
          </div>
        </SectionCard>

        {/* Section 10: Troubleshooting */}
        <SectionCard
          icon={Icon.warning}
          title="🔧 Troubleshooting"
          accent={C.orange}
        >
          <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "10px" }}>
            <div style={{ background: C.card, borderRadius: "10px", padding: "12px", border: "1px solid C.border" }}>
              <div style={{ fontSize: "12px", color: C.red, fontWeight: 700, marginBottom: "4px" }}>Map won't load</div>
              <div style={{ fontSize: "12px", color: C.muted }}>Check internet → try Leaflet fallback</div>
            </div>
            <div style={{ background: C.card, borderRadius: "10px", padding: "12px", border: "1px solid C.border" }}>
              <div style={{ fontSize: "12px", color: C.orange, fontWeight: 700, marginBottom: "4px" }}>Data not refreshing</div>
              <div style={{ fontSize: "12px", color: C.muted }}>Pull down to refresh → check connection</div>
            </div>
            <div style={{ background: C.card, borderRadius: "10px", padding: "12px", border: "1px solid C.border" }}>
              <div style={{ fontSize: "12px", color: C.purple, fontWeight: 700, marginBottom: "4px" }}>Can't export</div>
              <div style={{ fontSize: "12px", color: C.muted }}>Enable pop-ups → try different browser</div>
            </div>
            <div style={{ background: C.card, borderRadius: "10px", padding: "12px", border: "1px solid C.border" }}>
              <div style={{ fontSize: "12px", color: C.blue, fontWeight: 700, marginBottom: "4px" }}>Offline not working</div>
              <div style={{ fontSize: "12px", color: C.muted }}>Re-install PWA while online</div>
            </div>
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", fontSize: "12px", color: C.muted }}>
                      {Icon.wifi}
                      <span><strong>Offline use:</strong> First load online → caches map tiles & static data → works without internet after install</span>
                    </div>
        </SectionCard>

        {/* Section 11: Emergency Contacts */}
        <div
          style={{
            background: C.card,
            borderRadius: "14px",
            padding: "18px 22px",
            border: `2px solid ${C.red}`,
            display: "flex",
            gap: "20px",
            alignItems: "center",
            flexWrap: "wrap",
          }}
        >
          <div style={{ fontSize: "28px", color: C.red }}>🚨</div>
          <div>
            <div style={{ fontSize: "14px", fontWeight: 700, color: C.text, marginBottom: "4px" }}>Emergency Contacts</div>
            <div style={{ display: "flex", gap: "16px", flexWrap: "wrap", fontSize: "13px", color: C.muted, fontFamily: "monospace" }}>
              <span>Nepal Police Emergency: <strong>100</strong></span>
              <span>NDRRMA: <strong>+977-1-4262636</strong></span>
              <span>DHM Flood Forecasting: <strong>+977-1-4470393</strong></span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            textAlign: "center",
            marginTop: "6px",
            padding: "10px",
            fontSize: "11px",
            color: C.muted,
            borderTop: "1px solid C.divider",
          }}
        >
          Generated by Hermes Agent (Nous Research) · Data verified: August 29, 2026
        </div>
      </div>
    </div>
  );
}
