// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — RSS News Aggregate Route
// Generated by Hermes Agent (Nous Research)
//
// GET /api/rss-aggregate
// Server-side RSS aggregation from free news sources (no API key needed)
// ─────────────────────────────────────────────────────────────────────────────

export async function GET() {
  try {
    const rssFeeds = [
      "https://www.abc.net.au/news/feed/107086974/rss.xml",
      "https://www.nbcnews.com/feed/594643",
      "https://www.cbsnews.com/latest/rss/main",
      "https://watchers.news/feed/",
      "https://earthsky.org/feed/",
    ];

    const results = await Promise.allSettled(
      rssFeeds.map(async (url) => {
        const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
        if (!res.ok) return null;
        return res.text();
      })
    );

    // For now, return a success response with the count of fetched feeds
    // In production, parse XML and extract relevant Nepal flood articles
    const successfulFeeds = results.filter((r) => r.status === "fulfilled" && r.value).length;

    return Response.json({
      success: true,
      feeds_fetched: successfulFeeds,
      total_feeds: rssFeeds.length,
      last_updated: new Date().toISOString(),
    });
  } catch (err) {
    return Response.json({ success: false, error: String(err) }, { status: 500 });
  }
}
