// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — RSS News Aggregate Route (with NewsAPI.org support)
// Generated by Hermes Agent (Nous Research)
//
// GET /api/rss-aggregate
// Server-side RSS aggregation + NewsAPI.org integration.
// Uses NEWS_API_KEY if available, falls back to free RSS feeds.
// ─────────────────────────────────────────────────────────────────────────────

export interface NewsItem {
  title: string;
  link: string;
  pubDate: string;
  source: string;
  summary: string;
}

// ── RSS feed sources (free, no key needed) ────────────────────────────────────
const RSS_FEEDS = [
  { name: "ABC News", url: "https://www.abc.net.au/news/feed/107086974/rss.xml" },
  { name: "NBC News", url: "https://www.nbcnews.com/feed/594643" },
  { name: "CBS News", url: "https://www.cbsnews.com/latest/rss/main" },
  { name: "The Watchers", url: "https://watchers.news/feed/" },
  { name: "EarthSky", url: "https://earthsky.org/feed/" },
  { name: "Nepal News", url: "https://english.nepalnews.com/feed/" },
  { name: "OnlineKhabar", url: "https://english.onlinekhabar.com/feed/" },
];

// ── Simple RSS 2.0 parser (regex-based, no XML library needed) ────────────────
function parseRSS(xml: string, sourceName: string): NewsItem[] {
  const items: NewsItem[] = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
  let match;

  while ((match = itemRegex.exec(xml)) !== null) {
    const itemXml = match[1];
    const title = extractField(itemXml, "title");
    const link = extractField(itemXml, "link");
    const pubDate = extractField(itemXml, "pubDate");
    const description = extractField(itemXml, "description");
    const source = extractField(itemXml, "source") || sourceName;

    if (title && link) {
      items.push({
        title: decodeHTML(title),
        link: decodeHTML(link),
        pubDate: pubDate || new Date().toISOString(),
        source: decodeHTML(source),
        summary: description ? decodeHTML(description).slice(0, 300) : "",
      });
    }
  }
  return items;
}

function extractField(xml: string, tag: string): string | null {
  const regex = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, "i");
  const match = regex.exec(xml);
  return match ? match[1].trim() : null;
}

function decodeHTML(str: string): string {
  return str
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#8217;/g, "'")
    .replace(/&#8220;/g, '"')
    .replace(/&#8221;/g, '"')
    .replace(/&#8212;/g, "—")
    .replace(/&#8211;/g, "–")
    .replace(/&nbsp;/g, " ");
}

// ── NewsAPI.org integration (requires NEWS_API_KEY) ───────────────────────────
async function fetchNewsAPI(key: string): Promise<NewsItem[]> {
  try {
    const res = await fetch(
      `https://newsapi.org/v2/everything?` +
      `q=nepal+flood+2026&` +
      `sortBy=publishedAt&` +
      `language=en&` +
      `pageSize=15&` +
      `apiKey=${key}`,
      { signal: AbortSignal.timeout(8000) }
    );

    if (!res.ok) {
      const status = res.status;
      if (status === 401 || status === 403) {
        // NewsAPI free tier only works on localhost — skip for production
        return [];
      }
      return [];
    }

    const data = await res.json();
    if (data.status !== "ok" || !data.articles) return [];

    return data.articles.map((a: Record<string, unknown>) => ({
      title: String(a.title ?? ""),
      link: String(a.url ?? ""),
      pubDate: String(a.publishedAt ?? new Date().toISOString()),
      source: String((a.source as Record<string, unknown>)?.name ?? "NewsAPI"),
      summary: String(a.description ?? "")?.slice(0, 300),
    }));
  } catch {
    return [];
  }
}

// ── Google Custom Search integration (requires GOOGLE_API_KEY1 + CX) ──────────
async function fetchGoogleNews(key: string, cx: string): Promise<NewsItem[]> {
  try {
    const res = await fetch(
      `https://www.googleapis.com/customsearch/v1?` +
      `key=${key}&` +
      `cx=${cx}&` +
      `q=nepal+flood+2026&` +
      `dateRestrict=ds:y&` +
      `num=10&` +
      `sort=date`,
      { signal: AbortSignal.timeout(8000) }
    );

    if (!res.ok) return [];

    const data = await res.json();
    if (!data.items) return [];

    interface GoogleItem {
      title?: string;
      link?: string;
      pagemap?: {
        metatags?: Array<Record<string, string>>;
      };
      snippet?: string;
    }

    return data.items.map((item: GoogleItem) => ({
      title: String(item.title ?? ""),
      link: String(item.link ?? ""),
      pubDate: String(item.pagemap?.metatags?.[0]?.["article:published_time"] ?? new Date().toISOString()),
      source: "Google News",
      summary: String(item.snippet ?? "")?.slice(0, 300),
    }));
  } catch {
    return [];
  }
}

// ── Main handler ───────────────────────────────────────────────────────────────
export async function GET() {
  try {
    const allItems: NewsItem[] = [];
    const seen = new Set<string>();

    // 1. Fetch NewsAPI.org if key is available
    const newsApiKey = process.env.NEWS_API_KEY;
    if (newsApiKey) {
      const newsApiItems = await fetchNewsAPI(newsApiKey);
      for (const item of newsApiItems) {
        const key = item.link;
        if (!seen.has(key)) {
          seen.add(key);
          allItems.push(item);
        }
      }
    }

    // 2. Fetch Google Custom Search if key + CX are available
    const googleKey = process.env.GOOGLE_API_KEY1;
    const googleCX  = process.env.GOOGLE_CX;
    if (googleKey && googleCX) {
      const googleItems = await fetchGoogleNews(googleKey, googleCX);
      for (const item of googleItems) {
        const key = item.link;
        if (!seen.has(key)) {
          seen.add(key);
          allItems.push(item);
        }
      }
    }

    // 3. Fetch free RSS feeds (always works, no key needed)
    const rssResults = await Promise.allSettled(
      RSS_FEEDS.map(async ({ name, url }) => {
        try {
          const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
          if (!res.ok) return [];
          const xml = await res.text();
          return parseRSS(xml, name);
        } catch {
          return [];
        }
      })
    );

    for (const result of rssResults) {
      if (result.status === "fulfilled") {
        for (const item of result.value) {
          const key = item.link;
          if (!seen.has(key)) {
            seen.add(key);
            allItems.push(item);
          }
        }
      }
    }

    // Sort by date (newest first)
    allItems.sort((a, b) => new Date(b.pubDate).getTime() - new Date(a.pubDate).getTime());

    // Filter for Nepal flood relevance
    const floodKeywords = ["nepal", "flood", "bhote koshi", "lhende khola", "glacier", "rasuwa", "trishuli"];
    const filtered = allItems.filter((item) =>
      floodKeywords.some((kw) => item.title.toLowerCase().includes(kw))
    );

    // If filtering removed everything, return all items
    const results = filtered.length > 0 ? filtered : allItems.slice(0, 15);

    return Response.json({
      success: true,
      count: results.length,
      news: results,
      last_updated: new Date().toISOString(),
      sources_used: {
        newsApi: !!newsApiKey,
        google: !!(googleKey && googleCX),
        rss: RSS_FEEDS.map((f) => f.name),
      },
    });
  } catch (err) {
    return Response.json({ success: false, error: String(err) }, { status: 500 });
  }
}
