// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Type definitions
// Generated by Claude (Anthropic) — claude.ai
// ─────────────────────────────────────────────────────────────────────────────

export type Severity     = "critical" | "high" | "medium";
export type LocationType = "origin" | "border" | "settlement" | "town" | "district" | "junction" | "region";
export type AlertLevel   = "critical" | "warning" | "info";

export interface FloodOrigin {
  name:        string;
  lat:         number;
  lng:         number;
  time:        string;
  description: string;
  district:    string;
  type:        "origin";
}

export interface FloodLocation {
  id:       number;
  name:     string;
  lat:      number;
  lng:      number;
  time:     string;
  district: string;
  type:     LocationType;
  severity: Severity;
  detail:   string;
}

export interface TimelineEvent {
  time:   string;
  event:  string;
  detail: string;
  source: string;
}

export interface ActiveAlert {
  level:        AlertLevel;
  title:        string;
  detail:       string;
  dismissible?: boolean;
}

export interface MissingByNationality {
  country: string;
  count:   number;
  source:  string;
}

export interface LiveStats {
  deaths_nepal:        number;
  deaths_tibet:        number;
  deaths_total:        number;
  missing_nepal:       number;
  missing_foreigners:  number;
  missing_americans:   number;
  rescued:             number;
  impacted_total:      number;
  powerloss_mw:        number;
  bridges_destroyed:   number;
  roads_destroyed_km:  number;
  trucks_swept?:       number;
  countries_affected?: number;
  last_updated:        string;
  source:              string;
  fallback?:           boolean;
}

export interface GDACSAlert {
  alertLevel: "green" | "orange" | "red" | null;
  title:      string | null;
  link:       string | null;
}
