// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Root layout
// Generated by Claude (Anthropic) — claude.ai
// ─────────────────────────────────────────────────────────────────────────────

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title:       "Nepal Glacial Flood — Live Situation Map · 2026",
  description:
    "Live mapping and situation dashboard for the August 26 2026 Nepal glacial flood " +
    "(Bhote Koshi / Lhende Khola). Real coordinates, verified casualty data, animated flow path.",
  openGraph: {
    title:       "Nepal Glacial Flood — Live Situation Map",
    description: "Live mapping · verified data · agentic refresh · Aug 26 2026",
    type:        "website",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gray-950 text-white antialiased">{children}</body>
    </html>
  );
}
