// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Root Layout (PWA-enabled)
// Generated by Hermes Agent (Nous Research)
// ─────────────────────────────────────────────────────────────────────────────

import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title:       "Nepal Glacial Flood — Live Situation Map · 2026",
  description:
    "Live mapping and situation dashboard for the August 26 2026 Nepal glacial flood " +
    "(Bhote Koshi / Lhende Khola). Real coordinates, verified casualty data, animated flow path, " +
    "3D terrain, satellite imagery, river gauge data, and live news feed.",
  openGraph: {
    title:       "Nepal Glacial Flood — Live Situation Map",
    description: "Live mapping · verified data · agentic refresh · 3D terrain · Aug 26 2026",
    type:        "website",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Nepal Flood",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#030712",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/icons/icon-192.svg" />
      </head>
      <body className="bg-gray-950 text-white antialiased" suppressHydrationWarning>
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ("serviceWorker" in navigator) {
                window.addEventListener("load", () => {
                  navigator.serviceWorker.register("/sw.js");
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
