// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Root page
// Generated by Claude (Anthropic) — claude.ai
// ─────────────────────────────────────────────────────────────────────────────

import dynamic            from "next/dynamic";
import AlertBanner        from "@/components/AlertBanner";
import LiveDashboard      from "@/components/LiveDashboard";
import FloodTimeline      from "@/components/FloodTimeline";
import CoordinateTable    from "@/components/CoordinateTable";

// Map must be client-only (Mapbox/Leaflet use window)
const FloodMap = dynamic(() => import("@/components/FloodMap"), { ssr: false });

export default function Page() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">

      <AlertBanner />

      {/* Header */}
      <header className="px-6 py-4 border-b border-gray-800 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight">
            Nepal Glacial Flood — Live Situation Map
          </h1>
          <div className="text-xs text-gray-500 mt-0.5">
            August 26–29, 2026 · Bhote Koshi / Lhende Khola event
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="inline-block w-2 h-2 rounded-full bg-green-400 animate-pulse" />
          <span className="text-xs text-green-400 font-medium">LIVE</span>
        </div>
      </header>

      <main className="p-4 md:p-6 space-y-8">

        {/* Map + Dashboard */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-6">
          <div className="md:col-span-3 h-[500px] md:h-[600px] rounded-lg overflow-hidden">
            <FloodMap />
          </div>
          <div className="md:col-span-2">
            <LiveDashboard />
          </div>
        </div>

        {/* Timeline */}
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
            Event Timeline
          </h2>
          <FloodTimeline />
        </section>

        {/* Coordinate Table */}
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
            All Locations · Coordinates
          </h2>
          <CoordinateTable />
        </section>

      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 px-6 py-8 mt-8 text-xs text-gray-600 space-y-3">
        <div className="font-semibold text-gray-500">Data Sources</div>
        <ul className="space-y-1 list-disc list-inside">
          <li>Nepal Police official statements (primary authority)</li>
          <li>BIPAD Nepal Govt: <a href="https://bipadportal.gov.np/" className="text-blue-600 hover:underline">bipadportal.gov.np</a></li>
          <li>NDRRMA: <a href="https://ndrrma.gov.np/en" className="text-blue-600 hover:underline">ndrrma.gov.np</a></li>
          <li>UN OCHA ReliefWeb: <a href="https://reliefweb.int/country/npl" className="text-blue-600 hover:underline">reliefweb.int</a></li>
          <li>GDACS (UN/JRC): <a href="https://www.gdacs.org/" className="text-blue-600 hover:underline">gdacs.org</a></li>
          <li>USGS Earthquake Hazards: <a href="https://earthquake.usgs.gov/" className="text-blue-600 hover:underline">earthquake.usgs.gov</a></li>
          <li>ICIMOD (glacier analysis): <a href="https://www.icimod.org/" className="text-blue-600 hover:underline">icimod.org</a></li>
          <li>EarthSky science report: <a href="https://earthsky.org/earth/nepal-flash-flood-glacier-collapse-landslide-aug-26-2026/" className="text-blue-600 hover:underline">earthsky.org</a></li>
          <li>ABC News live blog · NBC News live blog · CBS News · The Watchers · AP · Reuters</li>
          <li>US State Dept · DFAT Australia · Red Cross</li>
        </ul>
        <p className="text-gray-700 border-t border-gray-800 pt-3 max-w-2xl">
          Data sourced from Nepal Police, Nepal Army, and major international news organisations.
          Figures are provisional and actively updated. This dashboard auto-refreshes every 60 seconds
          via a multi-source agentic pipeline (BIPAD → ReliefWeb → Anthropic web search → static fallback).
        </p>
        <p className="text-gray-700">
          Built with Next.js · Tailwind · Mapbox GL JS · Recharts · Anthropic API ·
          <strong className="text-gray-600"> Generated by Claude, Anthropic's AI assistant (claude.ai)</strong>
        </p>
      </footer>

    </div>
  );
}
