// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Root Page (Full Dashboard)
// Generated by Hermes Agent (Nous Research)
// ─────────────────────────────────────────────────────────────────────────────

import AlertBanner from "@/components/AlertBanner";
import LiveDashboard from "@/components/LiveDashboard";
import FloodTimeline from "@/components/FloodTimeline";
import CoordinateTable from "@/components/CoordinateTable";
import SatelliteComparison from "@/components/SatelliteComparison";
import RiverGaugeData from "@/components/RiverGaugeData";
import FloodExtentOverlay from "@/components/FloodExtentOverlay";
import RSSNewsAggregator from "@/components/RSSNewsAggregator";
import DataExport from "@/components/DataExport";
import LeafletFloodMap from "@/components/LeafletFloodMap";

export default function Page() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <AlertBanner />

      {/* Header */}
      <header className="px-6 py-4 border-b border-gray-800 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight">
            Nepal Glacial Flood — Live Situation Map
          </h1>
          <div className="text-xs text-gray-500 mt-0.5">
            August 26–29, 2026 · Bhote Koshi / Lhende Khola event
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="inline-block w-2 h-2 rounded-full bg-green-400 animate-pulse" />
          <span className="text-xs text-green-400 font-medium">LIVE</span>
        </div>
      </header>

      <main className="p-4 md:p-6 space-y-8">
        {/* Map + Dashboard Grid */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-6">
          <div className="md:col-span-3 h-[500px] md:h-[600px] rounded-lg overflow-hidden">
            <LeafletFloodMap />
          </div>
          <div className="md:col-span-2">
            <LiveDashboard />
          </div>
        </div>

        {/* Satellite + River Gauge Row */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
              Satellite Imagery
            </h2>
            <SatelliteComparison />
          </section>
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
              River Gauge Data
            </h2>
            <RiverGaugeData />
          </section>
        </div>

        {/* News + Export Row */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
              Live News Feed
            </h2>
            <RSSNewsAggregator />
          </section>
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
              Map Layers & Overlays
            </h2>
            <FloodExtentOverlay />
          </section>
        </div>

        {/* Timeline */}
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
            Event Timeline
          </h2>
          <FloodTimeline />
        </section>

        {/* Coordinate Table */}
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
            All Locations · Coordinates
          </h2>
          <CoordinateTable />
        </section>

        {/* Data Export */}
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-widest text-gray-400 mb-4">
            Export Data
          </h2>
          <DataExport />
        </section>

        {/* Field Guide Link */}
        <section className="bg-gray-800 rounded-lg p-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-semibold text-white">
                📋 Field Worker Guide
              </h2>
              <p className="text-sm text-gray-400 mt-1">
                How to use this dashboard in the field, offline installation, coordinate export, GPS usage
              </p>
            </div>
            <a
              href="/FIELD_GUIDE.md"
              target="_blank"
              className="bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg px-4 py-2 transition-colors"
            >
              Open Guide
            </a>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 px-6 py-8 mt-8 text-xs text-gray-600 space-y-3">
        <div className="font-semibold text-gray-500">Data Sources</div>
        <ul className="space-y-1 list-disc list-inside">
          <li>Nepal Police official statements (primary authority)</li>
          <li>BIPAD Nepal Govt: <a href="https://bipadportal.gov.np/" className="text-blue-600 hover:underline">bipadportal.gov.np</a></li>
          <li>NDRRMA: <a href="https://ndrrma.gov.np/en" className="text-blue-600 hover:underline">ndrrma.gov.np</a></li>
          <li>UN OCHA ReliefWeb: <a href="https://reliefweb.int/country/npl" className="text-blue-600 hover:underline">reliefweb.int</a></li>
          <li>GDACS (UN/JRC): <a href="https://www.gdacs.org/" className="text-blue-600 hover:underline">gdacs.org</a></li>
          <li>USGS Earthquake Hazards: <a href="https://earthquake.usgs.gov/" className="text-blue-600 hover:underline">earthquake.usgs.gov</a></li>
          <li>ICIMOD (glacier analysis): <a href="https://www.icimod.org/" className="text-blue-600 hover:underline">icimod.org</a></li>
          <li>DHM Nepal (river gauges): <a href="http://www.dhm.gov.np/" className="text-blue-600 hover:underline">dhm.gov.np</a></li>
          <li>Copernicus EMS (satellite): <a href="https://emergency.copernicus.eu/" className="text-blue-600 hover:underline">emergency.copernicus.eu</a></li>
          <li>ABC News live blog · NBC News live blog · CBS News · The Watchers · EarthSky · AP · Reuters</li>
          <li>US State Dept · DFAT Australia · Red Cross</li>
        </ul>
        <p className="text-gray-700 border-t border-gray-800 pt-3 max-w-2xl">
          Data sourced from Nepal Police, Nepal Army, and major international news organisations.
          Figures are provisional and actively updated. This dashboard auto-refreshes every 60 seconds
          via a multi-source pipeline (BIPAD → ReliefWeb → RSS news → static fallback).
        </p>
        <p className="text-gray-700">
          Built with Next.js · Tailwind · Leaflet · Recharts · Anthropic API (optional) ·
          <strong className="text-gray-600"> Generated by Hermes Agent (Nous Research)</strong>
        </p>
      </footer>
    </div>
  );
}
