// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Alert banner (full-width, top of page)
// Generated by Hermes Agent (Nous Research)
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useState } from "react";

export default function AlertBanner() {
  const [dismissed, setDismissed] = useState(false);
  if (dismissed) return null;

  return (
    <div className="bg-red-900/80 border-b border-red-700 text-white px-4 py-3
      flex items-center justify-between gap-4">
      <div className="flex items-center gap-3">
        <span className="inline-block w-2 h-2 rounded-full bg-red-400 animate-pulse shrink-0" />
        <div>
          <span className="font-semibold text-sm">ACTIVE EMERGENCY · Aug 29 2026 </span>
          <span className="text-red-200 text-sm">
            · Nepal Flood Forecasting Division: Bhotekoshi water levels rising again.
            Trishuli River bank residents — move to safe location immediately.
          </span>
        </div>
      </div>
      <button onClick={() => setDismissed(true)}
        className="text-red-300 hover:text-white shrink-0 text-sm">✕</button>
    </div>
  );
}
