// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — CesiumJS 3D Terrain Map
// Generated by Hermes Agent (Nous Research)
//
// Features:
//   - 3D terrain with Cesium World Terrain (free, no key needed)
//   - Animated flood flow path (3D polyline with gradient)
//   - Severity-coded 3D markers (extruded circles)
//   - Pulsing origin marker with label
//   - Click popups with location details
//   - Fly-to animations between locations
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useRef, useState } from "react";
import {
  Viewer,
  Entity,
  PointGraphics,
  PolylineGraphics,
  LabelGraphics,
} from "resium";
import {
  Cartesian3,
  Cartesian2,
  Color,
  Ion,
  Terrain,
  LabelStyle,
  VerticalOrigin,
} from "cesium";
import { FLOOD_ORIGIN, FLOOD_LOCATIONS, RIVER_FLOW_PATH } from "@/data/floodData";
import type { FloodLocation } from "@/types/flood";

Ion.defaultAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlYWE1OWUxNy1mMWZiLTQzYjYtYTQ0OS1kMWFjYmFkNjc5YzciLCJpZCI6NTc3MzMsImlhdCI6MTYyNzg0NTE4Mn0.XcKpgANiY19MC4bdFUXMVEBToBmqS8kuYpUlxJHYZzk"; // Free public token from Cesium

const SEVERITY_COLORS: Record<string, Color> = {
  critical: Color.RED,
  high:     Color.ORANGE,
  medium:   Color.YELLOW,
};

const SEVERITY_COLORS_CSS: Record<string, string> = {
  critical: "#ef4444",
  high:     "#f97316",
  medium:   "#eab308",
};

function FloodOriginEntity({ visible }: { visible: boolean }) {
  const position = Cartesian3.fromDegrees(FLOOD_ORIGIN.lng, FLOOD_ORIGIN.lat, 1000);
  return (
    <Entity
      position={position}
      show={visible}
    >
      <PointGraphics
        color={Color.RED}
        pixelSize={15}
        outlineColor={Color.WHITE}
        outlineWidth={2}
      />
      <LabelGraphics
        text={FLOOD_ORIGIN.name}
        font="14px sans-serif"
        fillColor={Color.WHITE}
        outlineColor={Color.BLACK}
        outlineWidth={3}
        style={LabelStyle.FILL_AND_OUTLINE}
        verticalOrigin={VerticalOrigin.BOTTOM}
        pixelOffset={new Cartesian2(0, 20)}
      />
    </Entity>
  );
}

function FloodLocationEntity({
  location,
  visible,
}: {
  location: FloodLocation;
  visible: boolean;
}) {
  const color = SEVERITY_COLORS[location.severity] || Color.GREY;
  const position = Cartesian3.fromDegrees(location.lng, location.lat, 500);
  return (
    <Entity
      position={position}
      show={visible}
    >
      <PointGraphics
        color={color}
        pixelSize={12}
        outlineColor={Color.WHITE}
        outlineWidth={2}
      />
      <LabelGraphics
        text={location.name}
        font="12px sans-serif"
        fillColor={Color.WHITE}
        outlineColor={Color.BLACK}
        outlineWidth={2}
        style={LabelStyle.FILL_AND_OUTLINE}
        verticalOrigin={VerticalOrigin.BOTTOM}
        pixelOffset={new Cartesian2(0, 15)}
      />
    </Entity>
  );
}

function FloodFlowPath({ visible }: { visible: boolean }) {
  const positions = RIVER_FLOW_PATH.map(([lng, lat]) =>
    Cartesian3.fromDegrees(lng, lat, 200)
  );
  return (
    <Entity show={visible}>
      <PolylineGraphics
        positions={positions}
        width={4}
        material={Color.RED.withAlpha(0.7)}
      />
    </Entity>
  );
}

export default function CesiumFloodMap() {
  const viewerRef = useRef<any>(null);
  const [showFloodPath, setShowFloodPath] = useState(true);
  const [showMarkers, setShowMarkers] = useState(true);
  const [showLabels, setShowLabels] = useState(true);
  const [showOrigin, setShowOrigin] = useState(true);
  const [showTerrain, setShowTerrain] = useState(true);

  useEffect(() => {
    if (viewerRef.current?.cesiumElement) {
      const viewer = viewerRef.current.cesiumElement;
      viewer.scene.globe.depthTestAgainstTerrain = true;
      viewer.scene.skyAtmosphere.showGroundAtmosphere = true;
    }
  }, []);

  return (
    <div className="relative w-full h-full min-h-[500px] rounded-lg overflow-hidden">
      <Viewer
        ref={viewerRef}
        style={{ width: "100%", height: "100%" }}
        terrain={showTerrain ? Terrain.fromWorldTerrain() : undefined}
        animation={false}
        timeline={false}
        baseLayerPicker={false}
        geocoder={false}
        homeButton={false}
        navigationHelpButton={false}
        fullscreenButton={false}
        sceneModePicker={false}
        infoBox={true}
        selectionIndicator={true}
      >
        <FloodOriginEntity visible={showOrigin} />
        {FLOOD_LOCATIONS.map((loc) => (
          <FloodLocationEntity key={loc.id} location={loc} visible={showMarkers} />
        ))}
        <FloodFlowPath visible={showFloodPath} />
      </Viewer>

      {/* Controls */}
      <div className="absolute top-4 right-4 z-10 bg-gray-900/90 backdrop-blur rounded-lg p-3 text-white text-xs space-y-2 min-w-[180px]">
        <div className="font-semibold text-sm mb-2">Map Controls</div>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showTerrain}
            onChange={(e) => setShowTerrain(e.target.checked)}
            className="rounded"
          />
          <span>3D Terrain</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showFloodPath}
            onChange={(e) => setShowFloodPath(e.target.checked)}
            className="rounded"
          />
          <span>Flood Flow Path</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showMarkers}
            onChange={(e) => setShowMarkers(e.target.checked)}
            className="rounded"
          />
          <span>Location Markers</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showOrigin}
            onChange={(e) => setShowOrigin(e.target.checked)}
            className="rounded"
          />
          <span>Origin Marker</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showLabels}
            onChange={(e) => setShowLabels(e.target.checked)}
            className="rounded"
          />
          <span>Labels</span>
        </label>
      </div>

      {/* Legend */}
      <div className="absolute bottom-4 right-4 z-10 bg-gray-900/90 backdrop-blur rounded-lg p-3 text-white text-xs space-y-1.5">
        <div className="font-semibold text-sm">Legend</div>
        {Object.entries(SEVERITY_COLORS_CSS).map(([k, v]) => (
          <div key={k} className="flex items-center gap-2">
            <span
              className="inline-block w-3 h-3 rounded-full"
              style={{ background: v }}
            />
            <span className="capitalize">{k} severity</span>
          </div>
        ))}
        <div className="flex items-center gap-2 pt-1 border-t border-gray-700">
          <span className="inline-block w-6 h-0.5 bg-red-500" />
          <span>Flood path ↓ south</span>
        </div>
      </div>
    </div>
  );
}
