// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Coordinate table with CSV export
// Generated by Claude (Anthropic) — claude.ai
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useState } from "react";
import { FLOOD_ORIGIN, FLOOD_LOCATIONS } from "@/data/floodData";
import type { FloodLocation, Severity }  from "@/types/flood";

type SortKey = "time" | "severity" | "district";

const SEVERITY_ORDER: Record<Severity, number> = { critical: 0, high: 1, medium: 2 };
const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "text-red-400",
  high:     "text-orange-400",
  medium:   "text-yellow-400",
};

// Synthesize origin as a location row
const ORIGIN_ROW: FloodLocation = {
  id: 0, name: FLOOD_ORIGIN.name, lat: FLOOD_ORIGIN.lat, lng: FLOOD_ORIGIN.lng,
  time: FLOOD_ORIGIN.time, district: FLOOD_ORIGIN.district,
  type: "origin", severity: "critical",
  detail: FLOOD_ORIGIN.description,
};
const ALL_ROWS = [ORIGIN_ROW, ...FLOOD_LOCATIONS];

function copyToClipboard(text: string, cb: () => void) {
  navigator.clipboard.writeText(text).then(cb).catch(() => {});
}

export default function CoordinateTable() {
  const [sortKey,     setSortKey]     = useState<SortKey>("time");
  const [sortAsc,     setSortAsc]     = useState(true);
  const [district,    setDistrict]    = useState("All");
  const [copiedId,    setCopiedId]    = useState<number | null>(null);
  const [csvCopied,   setCsvCopied]   = useState(false);

  const districts = ["All", ...Array.from(new Set(ALL_ROWS.map((r) => r.district)))];

  const sorted = [...ALL_ROWS]
    .filter((r) => district === "All" || r.district === district)
    .sort((a, b) => {
      let cmp = 0;
      if (sortKey === "severity") cmp = SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity];
      if (sortKey === "district") cmp = a.district.localeCompare(b.district);
      if (sortKey === "time")     cmp = a.time.localeCompare(b.time);
      return sortAsc ? cmp : -cmp;
    });

  function toggleSort(key: SortKey) {
    if (sortKey === key) setSortAsc((v) => !v);
    else { setSortKey(key); setSortAsc(true); }
  }

  function exportCSV() {
    const header = "name,district,lat,lng,time,severity,detail";
    const rows   = ALL_ROWS.map((r) =>
      `"${r.name}","${r.district}",${r.lat},${r.lng},"${r.time}","${r.severity}","${r.detail.replace(/"/g, '""')}"`
    );
    const csv    = [header, ...rows].join("\n");
    const blob   = new Blob([csv], { type: "text/csv" });
    const url    = URL.createObjectURL(blob);
    const a      = document.createElement("a");
    a.href = url; a.download = "nepal-flood-2026-coordinates.csv"; a.click();
    URL.revokeObjectURL(url);
    setCsvCopied(true);
    setTimeout(() => setCsvCopied(false), 2000);
  }

  const SortBtn = ({ k, label }: { k: SortKey; label: string }) => (
    <button onClick={() => toggleSort(k)}
      className="flex items-center gap-1 hover:text-white transition">
      {label}
      <span className="text-gray-600">{sortKey === k ? (sortAsc ? "↑" : "↓") : "↕"}</span>
    </button>
  );

  return (
    <div className="space-y-3">
      {/* Controls */}
      <div className="flex flex-wrap gap-3 items-center">
        <select value={district} onChange={(e) => setDistrict(e.target.value)}
          className="bg-gray-800 text-white text-sm rounded px-3 py-1.5 border border-gray-700">
          {districts.map((d) => <option key={d}>{d}</option>)}
        </select>
        <button onClick={exportCSV}
          className="bg-gray-700 hover:bg-gray-600 text-white text-sm rounded px-3 py-1.5 transition">
          {csvCopied ? "✓ Downloading…" : "Export CSV"}
        </button>
        <span className="text-gray-500 text-xs">{sorted.length} locations</span>
      </div>

      {/* Table */}
      <div className="overflow-x-auto rounded-lg border border-gray-800">
        <table className="w-full text-sm text-left">
          <thead className="bg-gray-800 text-gray-400 text-xs uppercase">
            <tr>
              <th className="px-3 py-2">Name</th>
              <th className="px-3 py-2"><SortBtn k="district" label="District" /></th>
              <th className="px-3 py-2">Lat</th>
              <th className="px-3 py-2">Lng</th>
              <th className="px-3 py-2"><SortBtn k="time"     label="Time Hit" /></th>
              <th className="px-3 py-2"><SortBtn k="severity" label="Severity" /></th>
              <th className="px-3 py-2">Copy</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-800">
            {sorted.map((row) => (
              <tr key={row.id}
                className="hover:bg-gray-800/60 transition-colors">
                <td className="px-3 py-2 text-white font-medium">{row.name}</td>
                <td className="px-3 py-2 text-gray-400">{row.district}</td>
                <td className="px-3 py-2 font-mono text-gray-300">{row.lat.toFixed(4)}</td>
                <td className="px-3 py-2 font-mono text-gray-300">{row.lng.toFixed(4)}</td>
                <td className="px-3 py-2 text-gray-400 whitespace-nowrap">{row.time}</td>
                <td className={`px-3 py-2 capitalize font-medium ${SEVERITY_COLOR[row.severity]}`}>
                  {row.severity}
                </td>
                <td className="px-3 py-2">
                  <button
                    onClick={() => copyToClipboard(`${row.lat},${row.lng}`, () => {
                      setCopiedId(row.id);
                      setTimeout(() => setCopiedId(null), 1500);
                    })}
                    className="text-xs text-gray-500 hover:text-white transition">
                    {copiedId === row.id ? "✓" : "Copy"}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Footer note */}
      <div className="text-[10px] text-gray-700">
        Coordinates verified by Claude · Anthropic · claude.ai · Aug 29 2026
      </div>
    </div>
  );
}
