// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Data Export (PDF, GeoJSON, KML)
// Generated by Hermes Agent (Nous Research)
//
// Export map data for use in QGIS, ArcGIS, Google Earth, coordination meetings
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { FLOOD_ORIGIN, FLOOD_LOCATIONS, RIVER_FLOW_PATH, LIVE_STATS } from "@/data/floodData";

export default function DataExport() {
  const exportGeoJSON = () => {
    const geojson = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {
            name: FLOOD_ORIGIN.name,
            type: "origin",
            time: FLOOD_ORIGIN.time,
            description: FLOOD_ORIGIN.description,
            district: FLOOD_ORIGIN.district,
          },
          geometry: {
            type: "Point",
            coordinates: [FLOOD_ORIGIN.lng, FLOOD_ORIGIN.lat],
          },
        },
        ...FLOOD_LOCATIONS.map((loc) => ({
          type: "Feature",
          properties: {
            name: loc.name,
            type: loc.type,
            severity: loc.severity,
            time: loc.time,
            district: loc.district,
            detail: loc.detail,
          },
          geometry: {
            type: "Point",
            coordinates: [loc.lng, loc.lat],
          },
        })),
        {
          type: "Feature",
          properties: {
            name: "Flood Flow Path",
            type: "flow-path",
          },
          geometry: {
            type: "LineString",
            coordinates: RIVER_FLOW_PATH,
          },
        },
      ],
    };

    const blob = new Blob([JSON.stringify(geojson, null, 2)], {
      type: "application/geo+json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "nepal-flood-2026.geojson";
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportKML = () => {
    const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Nepal Flood 2026</name>
    <description>Bhote Koshi / Lhende Khola flood event - Aug 26-29 2026</description>
    ${FLOOD_LOCATIONS.map(
      (loc) => `
    <Placemark>
      <name>${loc.name}</name>
      <description>${loc.detail}</description>
      <Point>
        <coordinates>${loc.lng},${loc.lat},0</coordinates>
      </Point>
    </Placemark>`
    ).join("")}
    <Placemark>
      <name>Flood Flow Path</name>
      <LineString>
        <coordinates>
          ${RIVER_FLOW_PATH.map(([lng, lat]) => `${lng},${lat},0`).join(" ")}
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>`;

    const blob = new Blob([kml], { type: "application/vnd.google-earth.kml+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "nepal-flood-2026.kml";
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportCSV = () => {
    const header = "name,district,lat,lng,time,severity,type,detail";
    const rows = FLOOD_LOCATIONS.map(
      (r) =>
        `"${r.name}","${r.district}",${r.lat},${r.lng},"${r.time}","${r.severity}","${r.type}","${r.detail.replace(/"/g, '""')}"`
    );
    const csv = [header, ...rows].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "nepal-flood-2026-coordinates.csv";
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPDF = () => {
    // Generate a simple printable report
    const report = `
<!DOCTYPE html>
<html>
<head>
  <title>Nepal Flood 2026 - Situation Report</title>
  <style>
    body { font-family: sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #1e293b; border-bottom: 2px solid #ef4444; padding-bottom: 10px; }
    h2 { color: #334155; margin-top: 30px; }
    .stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
    .stat { background: #f1f5f9; padding: 15px; border-radius: 8px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: bold; color: #1e293b; }
    .stat-label { font-size: 12px; color: #64748b; margin-top: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
    th { background: #f8fafc; font-weight: 600; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>Nepal Glacial Flood — Situation Report</h1>
  <p><strong>Event:</strong> Bhote Koshi / Lhende Khola flood</p>
  <p><strong>Date:</strong> August 26–29, 2026</p>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>

  <h2>Key Figures</h2>
  <div class="stat-grid">
    <div class="stat"><div class="stat-value">${LIVE_STATS.deaths_total}</div><div class="stat-label">Total Deaths</div></div>
    <div class="stat"><div class="stat-value">${LIVE_STATS.missing_nepal}</div><div class="stat-label">Missing (Nepal)</div></div>
    <div class="stat"><div class="stat-value">${LIVE_STATS.rescued}</div><div class="stat-label">Rescued</div></div>
    <div class="stat"><div class="stat-value">${LIVE_STATS.impacted_total}</div><div class="stat-label">Impacted</div></div>
    <div class="stat"><div class="stat-value">${LIVE_STATS.powerloss_mw} MW</div><div class="stat-label">Power Lost</div></div>
    <div class="stat"><div class="stat-value">${LIVE_STATS.bridges_destroyed}</div><div class="stat-label">Bridges Destroyed</div></div>
  </div>

  <h2>Affected Locations</h2>
  <table>
    <tr><th>Location</th><th>District</th><th>Severity</th><th>Time</th></tr>
    ${FLOOD_LOCATIONS.map((l) => `<tr><td>${l.name}</td><td>${l.district}</td><td>${l.severity}</td><td>${l.time}</td></tr>`).join("")}
  </table>

  <div class="footer">
    Source: Nepal Police, ABC News, NBC News, CBS News, USGS, ICIMOD<br>
    Generated by Nepal Flood Map Dashboard
  </div>
</body>
</html>`;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(report);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-3">
      <div className="text-xs text-gray-400 uppercase tracking-wide">
        Export Data
      </div>

      <div className="grid grid-cols-2 gap-2">
        <button
          onClick={exportGeoJSON}
          className="bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg px-3 py-2 transition-colors text-left"
        >
          <div className="font-medium">GeoJSON</div>
          <div className="text-[10px] text-gray-400">For QGIS / ArcGIS</div>
        </button>
        <button
          onClick={exportKML}
          className="bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg px-3 py-2 transition-colors text-left"
        >
          <div className="font-medium">KML</div>
          <div className="text-[10px] text-gray-400">For Google Earth</div>
        </button>
        <button
          onClick={exportCSV}
          className="bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg px-3 py-2 transition-colors text-left"
        >
          <div className="font-medium">CSV</div>
          <div className="text-[10px] text-gray-400">Spreadsheet / Database</div>
        </button>
        <button
          onClick={exportPDF}
          className="bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg px-3 py-2 transition-colors text-left"
        >
          <div className="font-medium">PDF Report</div>
          <div className="text-[10px] text-gray-400">Print / Share</div>
        </button>
      </div>

      <div className="text-[10px] text-gray-600 border-t border-gray-800 pt-2">
        Export all coordinates, stats, and map data for use in GIS software or coordination meetings.
      </div>
    </div>
  );
}
