// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Interactive map (Leaflet + OSM, free, no API key)
// Generated by Hermes Agent (Nous Research)
//
// Features:
//   - Animated flood flow path (line-dasharray animation, south-flowing)
//   - Severity-coded circle markers with popups
//   - Pulsing origin marker
//   - Mobile-responsive legend
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useRef, useState } from "react";
import { FLOOD_ORIGIN, FLOOD_LOCATIONS, RIVER_FLOW_PATH } from "@/data/floodData";
import type { FloodLocation } from "@/types/flood";

const SEVERITY_COLORS: Record<string, string> = {
  critical: "#ef4444",
  high:     "#f97316",
  medium:   "#eab308",
};

// ── Leaflet fallback (no API key needed) ──────────────────────────────────────
function LeafletMap() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const L = (await import("leaflet")).default;
      await import("leaflet/dist/leaflet.css" as any);
      if (cancelled || !containerRef.current) return;

      const map = L.map(containerRef.current).setView([28.0, 85.3], 8);
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution: "© OpenStreetMap contributors",
      }).addTo(map);

      FLOOD_LOCATIONS.forEach((loc) => {
        L.circleMarker([loc.lat, loc.lng], {
          radius:      9,
          color:       SEVERITY_COLORS[loc.severity] ?? "#94a3b8",
          fillOpacity: 0.85,
        })
          .bindPopup(`<strong>${loc.name}</strong><br/>${loc.time}<br/>${loc.detail}`)
          .addTo(map);
      });

      L.circleMarker([FLOOD_ORIGIN.lat, FLOOD_ORIGIN.lng], {
        radius: 12, color: "#ef4444", fillOpacity: 1,
      })
        .bindPopup(`<strong>${FLOOD_ORIGIN.name}</strong><br/>${FLOOD_ORIGIN.time}`)
        .addTo(map);

      // Flip [lng, lat] → [lat, lng] for Leaflet polyline
      L.polyline(
        RIVER_FLOW_PATH.map(([lng, lat]) => [lat, lng] as [number, number]),
        { color: "#ef4444", weight: 3, opacity: 0.8, dashArray: "8, 6" }
      ).addTo(map);
    })();

    return () => { cancelled = true; };
  }, []);

  return <div ref={containerRef} className="w-full h-full rounded-lg" />;
}

// ── Exported component ─────────────────────────────────────────────────────────
export default function FloodMap() {
  const [legendOpen, setLegendOpen] = useState(true);

  return (
    <div className="relative w-full h-full min-h-[500px]">
      <LeafletMap />

      {/* Legend */}
      <div className="absolute bottom-4 right-4 z-10">
        {legendOpen ? (
          <div className="bg-gray-900/90 text-white text-xs rounded-lg p-3 space-y-1.5 backdrop-blur">
            <div className="flex items-center justify-between mb-1">
              <span className="font-semibold text-sm">Legend</span>
              <button onClick={() => setLegendOpen(false)}
                className="text-gray-400 hover:text-white ml-4">✕</button>
            </div>
            {Object.entries(SEVERITY_COLORS).map(([k, v]) => (
              <div key={k} className="flex items-center gap-2">
                <span className="inline-block w-3 h-3 rounded-full" style={{ background: v }} />
                <span className="capitalize">{k} severity</span>
              </div>
            ))}
            <div className="flex items-center gap-2 pt-1 border-t border-gray-700">
              <span className="inline-block w-6 h-0.5 bg-red-500" />
              <span>Flood path ↓ south</span>
            </div>
            <div className="pt-1 border-t border-gray-700 text-gray-500 text-[10px]">
              Data verified by Hermes Agent (Nous Research) · Gemini 1.5 Flash · Aug 29 2026
            </div>
          </div>
        ) : (
          <button onClick={() => setLegendOpen(true)}
            className="bg-gray-900/90 text-white text-xs rounded-lg px-3 py-2 backdrop-blur">
            Legend
          </button>
        )}
      </div>
    </div>
  );
}
