// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Event timeline
// Generated by Hermes Agent (Nous Research)
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useRef, useState } from "react";
import { TIMELINE_EVENTS }             from "@/data/floodData";

export default function FloodTimeline() {
  const [visible,  setVisible]  = useState(false);
  const [atBottom, setAtBottom] = useState(true);
  const endRef    = useRef<HTMLDivElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => { setTimeout(() => setVisible(true), 100); }, []);

  const scrollToLatest = () => endRef.current?.scrollIntoView({ behavior: "smooth" });

  const onScroll = () => {
    const el = scrollRef.current;
    if (!el) return;
    setAtBottom(el.scrollTop + el.clientHeight >= el.scrollHeight - 20);
  };

  return (
    <div className="relative">
      <div
        ref={scrollRef}
        onScroll={onScroll}
        className="max-h-96 overflow-y-auto pr-2"
      >
        <div className="relative border-l-2 border-gray-700 ml-4 space-y-0">
          {TIMELINE_EVENTS.map((ev, i) => (
            <div
              key={i}
              className="relative pl-8 pb-8 transition-all duration-500"
              style={{
                opacity:   visible ? 1 : 0,
                transform: visible ? "translateY(0)" : "translateY(16px)",
                transitionDelay: `${i * 150}ms`,
              }}
            >
              {/* Dot */}
              <span className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2
                ${i === TIMELINE_EVENTS.length - 1
                  ? "bg-amber-400 border-amber-300 animate-pulse"
                  : "bg-gray-700 border-gray-500"}`}
              />
              {/* Time badge */}
              <span className="inline-block font-mono text-xs bg-gray-800 text-gray-300
                rounded px-2 py-0.5 mb-1">
                {ev.time}
              </span>
              {/* Title */}
              <div className={`font-semibold text-sm mb-1
                ${i === TIMELINE_EVENTS.length - 1 ? "text-amber-400" : "text-white"}`}>
                {ev.event}
                {i === TIMELINE_EVENTS.length - 1 && (
                  <span className="ml-2 text-xs font-normal text-amber-500">ONGOING</span>
                )}
              </div>
              {/* Detail */}
              <div className="text-sm text-gray-300">{ev.detail}</div>
              {/* Source */}
              <div className="text-[11px] text-gray-600 mt-1 italic">Source: {ev.source}</div>
            </div>
          ))}
          <div ref={endRef} />
        </div>
      </div>

      {!atBottom && (
        <button
          onClick={scrollToLatest}
          className="absolute bottom-2 right-2 bg-amber-500 text-black text-xs
            font-semibold rounded px-3 py-1 shadow-lg hover:bg-amber-400 transition"
        >
          Jump to latest ↓
        </button>
      )}
    </div>
  );
}
