// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Interactive Mapbox GL JS map
// Generated by Claude (Anthropic) — claude.ai
//
// Features:
//   - Animated flood flow path (line-dasharray animation, south-flowing)
//   - Severity-coded circle markers with popups
//   - Pulsing origin marker
//   - Leaflet/OSM fallback if NEXT_PUBLIC_MAPBOX_TOKEN is absent
//   - Mobile-responsive legend
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useRef, useState } from "react";
import { FLOOD_ORIGIN, FLOOD_LOCATIONS, RIVER_FLOW_PATH } from "@/data/floodData";
import type { FloodLocation } from "@/types/flood";

const SEVERITY_COLORS: Record<string, string> = {
  critical: "#ef4444",
  high:     "#f97316",
  medium:   "#eab308",
};

// ── Mapbox implementation ─────────────────────────────────────────────────────
function MapboxMap() {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef       = useRef<any>(null);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      const mapboxgl = (await import("mapbox-gl")).default;
      await import("mapbox-gl/dist/mapbox-gl.css" as any); // eslint-disable-line @typescript-eslint/no-explicit-any
      if (cancelled || !containerRef.current) return;

      mapboxgl.accessToken = process.env.NEXT_PUBLIC_MAPBOX_TOKEN!;

      const map = new mapboxgl.Map({
        container: containerRef.current,
        style:     "mapbox://styles/mapbox/dark-v11",
        center:    [85.3, 28.0],
        zoom:      7.5,
      });
      mapRef.current = map;

      map.on("load", () => {
        // ── Flow path ───────────────────────────────────────────────────────
        map.addSource("flood-path", {
          type: "geojson",
          data: {
            type:     "Feature",
            geometry: { type: "LineString", coordinates: RIVER_FLOW_PATH },
            properties: {},
          },
        });
        // Glow layer (wider, semi-transparent)
        map.addLayer({
          id:     "flood-path-glow",
          type:   "line",
          source: "flood-path",
          paint:  { "line-color": "#ef4444", "line-width": 8, "line-opacity": 0.25 },
        });
        // Animated dash layer
        map.addLayer({
          id:     "flood-path-animated",
          type:   "line",
          source: "flood-path",
          paint: {
            "line-color":      "#ef4444",
            "line-width":      3,
            "line-dasharray":  [0, 4, 3],
          },
        });

        // Animate dasharray to simulate flow
        let step = 0;
        const dashArraySeq = [
          [0, 4, 3], [0.5, 4, 2.5], [1, 4, 2], [1.5, 4, 1.5],
          [2, 4, 1], [2.5, 4, 0.5], [3, 4, 0], [0, 0.5, 3, 3.5],
        ];
        function animateDash() {
          map.setPaintProperty(
            "flood-path-animated",
            "line-dasharray",
            dashArraySeq[step % dashArraySeq.length]
          );
          step++;
          requestAnimationFrame(animateDash);
        }
        animateDash();

        // ── Location markers ────────────────────────────────────────────────
        map.addSource("locations", {
          type: "geojson",
          data: {
            type:     "FeatureCollection",
            features: FLOOD_LOCATIONS.map((loc) => ({
              type:       "Feature",
              geometry:   { type: "Point", coordinates: [loc.lng, loc.lat] },
              properties: loc,
            })),
          },
        });

        map.addLayer({
          id:     "locations-circle",
          type:   "circle",
          source: "locations",
          paint: {
            "circle-radius":       8,
            "circle-color":        [
              "match",
              ["get", "severity"],
              "critical", "#ef4444",
              "high",     "#f97316",
              "medium",   "#eab308",
              "#94a3b8",
            ],
            "circle-stroke-color": "#0f172a",
            "circle-stroke-width": 2,
            "circle-opacity":      0.9,
          },
        });

        // Popup on click
        map.on("click", "locations-circle", (e: any) => {
          if (!e.features?.length) return;
          const props = e.features[0].properties as FloodLocation;
          new mapboxgl.Popup({ maxWidth: "320px" })
            .setLngLat(e.lngLat)
            .setHTML(`
              <div style="font-family:sans-serif;color:#1e293b;padding:4px">
                <strong style="font-size:14px">${props.name}</strong>
                <div style="margin:6px 0;font-size:12px;color:#64748b">
                  ${props.district} · ${props.time}
                </div>
                <div style="font-size:11px;color:#94a3b8;margin-bottom:6px">
                  ${props.lat.toFixed(4)}°N, ${props.lng.toFixed(4)}°E
                </div>
                <div style="font-size:12px">${props.detail}</div>
              </div>
            `)
            .addTo(map);
        });
        map.on("mouseenter", "locations-circle", () => {
          map.getCanvas().style.cursor = "pointer";
        });
        map.on("mouseleave", "locations-circle", () => {
          map.getCanvas().style.cursor = "";
        });

        // ── Pulsing origin marker ───────────────────────────────────────────
        const el = document.createElement("div");
        el.className = "pulse-marker";
        el.style.cssText = `
          width:20px;height:20px;border-radius:50%;
          background:#ef4444;box-shadow:0 0 0 0 rgba(239,68,68,0.6);
          animation:pulse 2s infinite;
        `;
        const style = document.createElement("style");
        style.textContent = `
          @keyframes pulse {
            0%   { box-shadow: 0 0 0 0 rgba(239,68,68,0.6); }
            70%  { box-shadow: 0 0 0 14px rgba(239,68,68,0); }
            100% { box-shadow: 0 0 0 0 rgba(239,68,68,0); }
          }
        `;
        document.head.appendChild(style);

        new mapboxgl.Marker({ element: el })
          .setLngLat([FLOOD_ORIGIN.lng, FLOOD_ORIGIN.lat])
          .setPopup(
            new mapboxgl.Popup({ offset: 20 }).setHTML(
              `<strong>${FLOOD_ORIGIN.name}</strong><br/>
               <small>${FLOOD_ORIGIN.time}</small><br/>
               <small>${FLOOD_ORIGIN.description.slice(0, 120)}…</small>`
            )
          )
          .addTo(map);
      });
    })();

    return () => {
      cancelled = true;
      mapRef.current?.remove();
    };
  }, []);

  return <div ref={containerRef} className="w-full h-full rounded-lg" />;
}

// ── Leaflet fallback (no API key needed) ──────────────────────────────────────
function LeafletMap() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const L = (await import("leaflet")).default;
      await import("leaflet/dist/leaflet.css" as any); // eslint-disable-line @typescript-eslint/no-explicit-any
      if (cancelled || !containerRef.current) return;

      const map = L.map(containerRef.current).setView([28.0, 85.3], 8);
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution: "© OpenStreetMap contributors",
      }).addTo(map);

      FLOOD_LOCATIONS.forEach((loc) => {
        L.circleMarker([loc.lat, loc.lng], {
          radius:      9,
          color:       SEVERITY_COLORS[loc.severity] ?? "#94a3b8",
          fillOpacity: 0.85,
        })
          .bindPopup(`<strong>${loc.name}</strong><br/>${loc.time}<br/>${loc.detail}`)
          .addTo(map);
      });

      L.circleMarker([FLOOD_ORIGIN.lat, FLOOD_ORIGIN.lng], {
        radius: 12, color: "#ef4444", fillOpacity: 1,
      })
        .bindPopup(`<strong>${FLOOD_ORIGIN.name}</strong><br/>${FLOOD_ORIGIN.time}`)
        .addTo(map);

      L.polyline(
        RIVER_FLOW_PATH.map(([lng, lat]) => [lat, lng] as [number, number]),
        { color: "#ef4444", weight: 3, opacity: 0.8, dashArray: "8, 6" }
      ).addTo(map);
    })();

    return () => { cancelled = true; };
  }, []);

  return <div ref={containerRef} className="w-full h-full rounded-lg" />;
}

// ── Exported component (auto-selects based on token presence) ─────────────────
export default function FloodMap() {
  const hasToken = Boolean(process.env.NEXT_PUBLIC_MAPBOX_TOKEN);
  const [legendOpen, setLegendOpen] = useState(true);

  return (
    <div className="relative w-full h-full min-h-[500px]">
      {hasToken ? <MapboxMap /> : <LeafletMap />}

      {/* Legend */}
      <div className="absolute bottom-4 right-4 z-10">
        {legendOpen ? (
          <div className="bg-gray-900/90 text-white text-xs rounded-lg p-3 space-y-1.5 backdrop-blur">
            <div className="flex items-center justify-between mb-1">
              <span className="font-semibold text-sm">Legend</span>
              <button onClick={() => setLegendOpen(false)}
                className="text-gray-400 hover:text-white ml-4">✕</button>
            </div>
            {Object.entries(SEVERITY_COLORS).map(([k, v]) => (
              <div key={k} className="flex items-center gap-2">
                <span className="inline-block w-3 h-3 rounded-full" style={{ background: v }} />
                <span className="capitalize">{k} severity</span>
              </div>
            ))}
            <div className="flex items-center gap-2 pt-1 border-t border-gray-700">
              <span className="inline-block w-6 h-0.5 bg-red-500" />
              <span>Flood path ↓ south</span>
            </div>
            {/* Generated by Claude note */}
            <div className="pt-1 border-t border-gray-700 text-gray-500 text-[10px]">
              Data verified by Claude · Anthropic · Aug 29 2026
            </div>
          </div>
        ) : (
          <button onClick={() => setLegendOpen(true)}
            className="bg-gray-900/90 text-white text-xs rounded-lg px-3 py-2 backdrop-blur">
            Legend
          </button>
        )}
      </div>
    </div>
  );
}
