// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Flood Extent & Infrastructure Overlay
// Generated by Hermes Agent (Nous Research)
//
// Shows flood extent polygons from satellite observations + critical infrastructure
// Data sources: Copernicus EMS, UN-SAT, OpenStreetMap
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useState } from "react";

interface OverlayLayer {
  id: string;
  name: string;
  description: string;
  source: string;
  enabled: boolean;
}

export default function FloodExtentOverlay() {
  const [layers, setLayers] = useState<OverlayLayer[]>([
    {
      id: "flood-extent",
      name: "Flood Extent (Satellite)",
      description: "Observed flood extent from Sentinel-1 SAR",
      source: "Copernicus EMS / UN-SAT",
      enabled: true,
    },
    {
      id: "infrastructure",
      name: "Critical Infrastructure",
      description: "Hospitals, schools, bridges, roads",
      source: "OpenStreetMap",
      enabled: false,
    },
    {
      id: "evacuation",
      name: "Evacuation Routes",
      description: "Designated evacuation corridors",
      source: "Nepal Government",
      enabled: false,
    },
    {
      id: "population",
      name: "Population Density",
      description: "WorldPop 2020 estimates",
      source: "WorldPop",
      enabled: false,
    },
    {
      id: "landslide",
      name: "Landslide Risk Zones",
      description: "ICIMOD landslide susceptibility",
      source: "ICIMOD",
      enabled: false,
    },
  ]);

  const toggleLayer = (id: string) => {
    setLayers((prev) =>
      prev.map((l) => (l.id === id ? { ...l, enabled: !l.enabled } : l))
    );
  };

  return (
    <div className="space-y-3">
      <div className="text-xs text-gray-400 uppercase tracking-wide">
        Map Layers & Overlays
      </div>

      <div className="space-y-2">
        {layers.map((layer) => (
          <div
            key={layer.id}
            className={`bg-gray-800 rounded-lg p-3 cursor-pointer transition-colors ${
              layer.enabled ? "ring-1 ring-blue-500" : ""
            }`}
            onClick={() => toggleLayer(layer.id)}
          >
            <div className="flex items-center justify-between">
              <div className="text-sm text-white font-medium">{layer.name}</div>
              <div
                className={`w-8 h-4 rounded-full transition-colors ${
                  layer.enabled ? "bg-blue-500" : "bg-gray-600"
                }`}
              >
                <div
                  className={`w-4 h-4 rounded-full bg-white transition-transform ${
                    layer.enabled ? "translate-x-4" : ""
                  }`}
                />
              </div>
            </div>
            <div className="text-[10px] text-gray-400 mt-1">
              {layer.description}
            </div>
            <div className="text-[10px] text-gray-600 mt-1">
              Source: {layer.source}
            </div>
          </div>
        ))}
      </div>

      <div className="text-[10px] text-gray-600 border-t border-gray-800 pt-2">
        Toggle layers to overlay on the map. Data from Copernicus EMS, UN-SAT,
        OpenStreetMap, and ICIMOD.
      </div>
    </div>
  );
}
