// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Live stats dashboard
// Generated by Claude (Anthropic) — claude.ai
//
// Auto-refreshes every 60s via /api/refresh (multi-source agentic pipeline).
// Also polls GDACS every 5 min for secondary event alerts.
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useRef, useState } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { LIVE_STATS, ACTIVE_ALERTS, MISSING_BY_NATIONALITY } from "@/data/floodData";
import { checkGDACS } from "@/lib/gdacs";
import type { LiveStats, ActiveAlert, GDACSAlert } from "@/types/flood";

const REFRESH_INTERVAL_MS  = 60_000;  // stats
const GDACS_INTERVAL_MS    = 300_000; // GDACS alert check

const SEVERITY_BG: Record<string, string> = {
  critical: "border-red-500",
  warning:  "border-orange-400",
  info:     "border-blue-400",
};

function StatCard({ label, value, unit }: { label: string; value: number; unit?: string }) {
  const prevRef  = useRef(value);
  const [flash, setFlash] = useState(false);

  useEffect(() => {
    if (value !== prevRef.current) {
      setFlash(true);
      setTimeout(() => setFlash(false), 600);
      prevRef.current = value;
    }
  }, [value]);

  return (
    <div className={`bg-gray-800 rounded-lg p-4 transition-transform duration-300 ${flash ? "scale-105" : ""}`}>
      <div className="text-2xl font-bold text-white tabular-nums">
        {value.toLocaleString()}{unit && <span className="text-sm font-normal text-gray-400 ml-1">{unit}</span>}
      </div>
      <div className="text-xs text-gray-400 mt-1">{label}</div>
    </div>
  );
}

export default function LiveDashboard() {
  const [stats,    setStats]    = useState<LiveStats>(LIVE_STATS);
  const [alerts,   setAlerts]   = useState<ActiveAlert[]>(ACTIVE_ALERTS);
  const [gdacs,    setGdacs]    = useState<GDACSAlert | null>(null);
  const [isStale,  setIsStale]  = useState(false);
  const lastFetch = useRef(Date.now());

  async function refresh() {
    try {
      const res  = await fetch("/api/refresh", { method: "POST" });
      const data = await res.json() as LiveStats;
      setStats(data);
      lastFetch.current = Date.now();
      setIsStale(false);
    } catch {
      setIsStale(true);
    }
  }

  async function pollGDACS() {
    const alert = await checkGDACS();
    setGdacs(alert);
  }

  useEffect(() => {
    refresh();
    pollGDACS();
    const statsTimer = setInterval(refresh,    REFRESH_INTERVAL_MS);
    const gdacsTimer = setInterval(pollGDACS,  GDACS_INTERVAL_MS);
    const staleTimer = setInterval(() => {
      setIsStale(Date.now() - lastFetch.current > 5 * 60_000);
    }, 30_000);
    return () => { clearInterval(statsTimer); clearInterval(gdacsTimer); clearInterval(staleTimer); };
  }, []);

  const dismissAlert = (i: number) => {
    setAlerts((prev) => prev.filter((_, idx) => idx !== i));
  };

  return (
    <div className="space-y-4 text-white">

      {/* Live badge */}
      <div className="flex items-center gap-2">
        <span className={`inline-block w-2 h-2 rounded-full ${isStale ? "bg-amber-400" : "bg-green-400 animate-pulse"}`} />
        <span className="text-xs text-gray-400">
          {isStale ? "Data may be stale" : "Live"} · refreshes every 60s
        </span>
        {stats.fallback && (
          <span className="text-xs text-amber-400 ml-2">(cached data)</span>
        )}
      </div>

      {/* GDACS secondary alert */}
      {gdacs?.alertLevel && gdacs.alertLevel !== "green" && (
        <div className={`border-l-4 rounded p-3 text-sm ${gdacs.alertLevel === "red" ? "border-red-500 bg-red-950/40" : "border-orange-400 bg-orange-950/40"}`}>
          <div className="font-semibold">⚠ GDACS {gdacs.alertLevel.toUpperCase()} Alert</div>
          <div className="text-gray-300 mt-1">{gdacs.title}</div>
          {gdacs.link && <a href={gdacs.link} target="_blank" rel="noreferrer" className="text-blue-400 text-xs mt-1 block">View on GDACS →</a>}
        </div>
      )}

      {/* Active alerts */}
      {alerts.map((alert, i) => (
        <div key={i} className={`border-l-4 rounded p-3 text-sm bg-gray-800/60 ${SEVERITY_BG[alert.level]}`}>
          <div className="flex justify-between items-start">
            <span className="font-semibold">{alert.title}</span>
            {alert.dismissible !== false ? (
              <button onClick={() => dismissAlert(i)} className="text-gray-500 hover:text-white ml-2 text-xs">✕</button>
            ) : (
              <span className="text-gray-600 text-xs ml-2" title="Cannot dismiss — active critical alert">🔒</span>
            )}
          </div>
          <div className="text-gray-300 mt-1">{alert.detail}</div>
        </div>
      ))}

      {/* Stat grid */}
      <div className="grid grid-cols-2 gap-3">
        <StatCard label="Deaths (Nepal)"      value={stats.deaths_nepal} />
        <StatCard label="Deaths (Tibet)"      value={stats.deaths_tibet} />
        <StatCard label="Missing (Nepal)"     value={stats.missing_nepal} />
        <StatCard label="Missing (foreigners)"value={stats.missing_foreigners} />
        <StatCard label="Americans missing"   value={stats.missing_americans} />
        <StatCard label="Rescued / airlifted" value={stats.rescued} />
        <StatCard label="People impacted"     value={stats.impacted_total} />
        <StatCard label="Power lost"          value={stats.powerloss_mw} unit="MW" />
        <StatCard label="Bridges destroyed"   value={stats.bridges_destroyed} />
        <StatCard label="Roads destroyed"     value={stats.roads_destroyed_km} unit="km" />
      </div>

      {/* Missing by nationality chart */}
      <div>
        <div className="text-xs text-gray-400 mb-2 uppercase tracking-wide">Missing by Nationality</div>
        <ResponsiveContainer width="100%" height={160}>
          <BarChart data={MISSING_BY_NATIONALITY} layout="vertical" margin={{ left: 90 }}>
            <XAxis type="number" tick={{ fontSize: 11, fill: "#94a3b8" }} />
            <YAxis type="category" dataKey="country" tick={{ fontSize: 11, fill: "#94a3b8" }} width={90} />
            <Tooltip
              contentStyle={{ background: "#1e293b", border: "none", fontSize: 12 }}
              formatter={(v: number, _: string, entry: any) =>
                [`${v} missing`, entry.payload.source]}
            />
            <Bar dataKey="count" radius={[0, 4, 4, 0]}>
              {MISSING_BY_NATIONALITY.map((_, i) => (
                <Cell key={i} fill={i === 0 ? "#ef4444" : i === 1 ? "#f97316" : "#eab308"} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Source attribution */}
      <div className="text-[10px] text-gray-600 border-t border-gray-800 pt-2">
        Source: {stats.source} · Updated: {new Date(stats.last_updated).toUTCString()}
        <br />
        Built with Next.js · Tailwind · Leaflet · Recharts · Free APIs only
        <strong className="text-gray-600"> · Hermes Agent (Nous Research)</strong>
      </div>
    </div>
  );
}
