// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Live Time Header
// Generated by Hermes Agent (Nous Research)
//
// Shows current UTC time + Nepal Time (NPT) in the header, updates every second.
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useState } from "react";

export default function LiveTimeHeader() {
  const [time, setTime] = useState<string>("");
  const [npt, setNpt] = useState<string>("");

  useEffect(() => {
    function tick() {
      const now = new Date();

      // UTC
      setTime(now.toUTCString().replace("GMT", "UTC"));

      // Nepal Time = UTC + 5:45
      const nptDate = new Date(now.getTime() + 5.75 * 3600 * 1000);
      const h = String(nptDate.getUTCHours()).padStart(2, "0");
      const m = String(nptDate.getUTCMinutes()).padStart(2, "0");
      const s = String(nptDate.getUTCSeconds()).padStart(2, "0");
      const d = nptDate.getUTCDate().toString().padStart(2, "0");
      const mo = (nptDate.getUTCMonth() + 1).toString().padStart(2, "0");
      const yr = nptDate.getUTCFullYear();
      setNpt(`${d}/${mo}/${yr} ${h}:${m}:${s} NPT`);
    }
    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, []);

  return (
    <div className="flex items-center gap-3 text-xs text-gray-500">
      <span className="inline-block w-2 h-2 rounded-full bg-green-400 animate-pulse" />
      <span className="text-xs text-green-400 font-medium">LIVE</span>
      <span className="text-gray-600">·</span>
      <span className="font-mono tabular-nums">{time}</span>
      <span className="text-gray-600">·</span>
      <span className="font-mono tabular-nums text-amber-400">{npt}</span>
    </div>
  );
}
