// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Free RSS News Aggregator
// Generated by Hermes Agent (Nous Research)
// //
// Fetches from /api/rss-aggregate which aggregates:
// - NewsAPI.org (requires NEWS_API_KEY)
// - Google Custom Search (requires GOOGLE_API_KEY1-7 + GOOGLE_CX) — multi-key fallback
// - Free RSS feeds: ABC, NBC, CBS, The Watchers, EarthSky, Nepal News, OnlineKhabar
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useEffect, useState } from "react";

interface NewsItem {
  title: string;
  link: string;
  pubDate: string;
  source: string;
  summary: string;
}

interface AggregateResponse {
  success: boolean;
  count: number;
  news: NewsItem[];
  last_updated: string;
  sources_used: {
    newsApi: boolean;
    google: boolean;
    rss: string[];
  };
  error?: string;
}

// Mock data for demo (used when API fails or during initial load)
const MOCK_NEWS: NewsItem[] = [
  {
    title: "Nepal Flood Forecasting Division: Bhotekoshi water levels rising again",
    link: "https://www.abc.net.au/news/2026-08-28/nepal-tibet-floods-live-updates/107086974",
    pubDate: "2026-08-29T02:20:00Z",
    source: "ABC News",
    summary:
      "Nepal Flood Forecasting Division acting on China data warns Bhotekoshi water levels rising. Trishuli River bank residents ordered to safe locations immediately.",
  },
  {
    title: "38 Australians missing in Nepal floods — DFAT confirms",
    link: "https://www.abc.net.au/news/2026-08-29/australians-missing-nepal-floods",
    pubDate: "2026-08-29T01:00:00Z",
    source: "ABC News",
    summary:
      "Department of Foreign Affairs and Trade confirms 38 Australians unaccounted for in Nepal flood zone. Consular assistance being provided.",
  },
  {
    title: "90 Americans missing in Nepal glacial flood — State Dept",
    link: "https://www.cbsnews.com/news/nepal-flood-rescue-efforts-death-toll/",
    pubDate: "2026-08-29T00:30:00Z",
    source: "CBS News",
    summary:
      "US State Department confirms 90 Americans missing. Tommy Pigott confirms figure on Fox News. Rescue operations ongoing.",
  },
  {
    title: "Secondary barrier lake overflowing on Tibet side — Nepal Police",
    link: "https://watchers.news/2026-08-28/nepal-flood-secondary-lake",
    pubDate: "2026-08-28T18:00:00Z",
    source: "The Watchers",
    summary:
      "Nepal Police issue fresh alert: newly formed barrier lake on Tibet side overflowing. Rescue operations temporarily suspended in high-risk zones.",
  },
  {
    title: "3,000+ airlifted to safety as death toll reaches 584",
    link: "https://www.cbsnews.com/news/nepal-flood-rescue-efforts-death-toll/",
    pubDate: "2026-08-28T12:00:00Z",
    source: "CBS News",
    summary:
      "Helicopter sorties intensify. 3,000+ airlifted to Kathmandu and Trishuli camp. Nepal Army, Police, Armed Police Force deploy 14,000+ personnel.",
  },
  {
    title: "Climate change likely factor in Nepal glacier collapse — scientists",
    link: "https://earthsky.org/earth/nepal-flash-flood-glacier-collapse-landslide-aug-26-2026/",
    pubDate: "2026-08-27T10:00:00Z",
    source: "EarthSky",
    summary:
      "Scientists cite climate change as likely contributing factor to Lhende Khola glacier collapse. ICIMOD satellite imagery confirms glacial source.",
  },
];

// ── Client-safe date formatter ─────────────────────────────────────────────────
// Returns "" during SSR and before client mount so server and client render match.
// After mount, fills in the formatted date.
function formattedDate(isoString: string): string {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);
  if (!mounted) return "";
  return new Date(isoString).toLocaleString();
}

export default function RSSNewsAggregator() {
  const [news, setNews] = useState<NewsItem[]>(MOCK_NEWS);
  const [loading, setLoading] = useState(false);
  const [lastFetch, setLastFetch] = useState<string>(new Date().toISOString());
  const [sources, setSources] = useState<AggregateResponse["sources_used"]>({
    newsApi: false,
    google: false,
    rss: [],
  });

  useEffect(() => {
    fetchNews();
  }, []);

  const fetchNews = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/rss-aggregate");
      const data: AggregateResponse = await res.json();
      if (data.success && data.news.length > 0) {
        setNews(data.news);
        setSources(data.sources_used);
      }
      setLastFetch(data.last_updated);
    } catch {
      // Keep mock data on error
    } finally {
      setLoading(false);
    }
  };

  const refresh = () => {
    fetchNews();
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div className="text-xs text-gray-400 uppercase tracking-wide">
          Live News Feed
        </div>
        <button
          onClick={refresh}
          disabled={loading}
          className="text-[10px] text-blue-400 hover:text-blue-300 disabled:text-gray-500"
        >
          {loading ? "Refreshing..." : "Refresh"}
        </button>
      </div>

      <div className="text-[10px] text-gray-500">
        Sources: {sources.newsApi && "NewsAPI.org "}{sources.google && "Google News "}
        {sources.rss.length > 0 && `RSS: ${sources.rss.join(", ")}`}
      </div>

      <div className="space-y-2 max-h-96 overflow-y-auto pr-2">
        {news.map((item, i) => (
          <a
            key={i}
            href={item.link}
            target="_blank"
            rel="noreferrer"
            className="block bg-gray-800 rounded-lg p-3 hover:bg-gray-700 transition-colors"
          >
            <div className="flex items-start justify-between gap-2">
              <div className="text-sm text-white font-medium">{item.title}</div>
              <span className="text-[10px] text-gray-500 shrink-0">
                {item.source}
              </span>
            </div>
            <div className="text-[10px] text-gray-400 mt-1 line-clamp-2">
              {item.summary}
            </div>
            <div className="text-[10px] text-gray-600 mt-1">
              {formattedDate(item.pubDate)}
            </div>
          </a>
        ))}
      </div>

      <div className="text-[10px] text-gray-600 border-t border-gray-800 pt-2">
        Last fetched: {formattedDate(lastFetch)} ·{' '}
        {sources.newsApi || sources.google ? "Live APIs + " : ""}Free RSS feeds
      </div>
    </div>
  );
}
