// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Satellite Imagery Comparison Slider
// Generated by Hermes Agent (Nous Research)
//
// Before/after satellite imagery comparison using Sentinel Hub / Copernicus
// Free, no API key needed for basic usage
// ─────────────────────────────────────────────────────────────────────────────

"use client";

import { useState } from "react";

export default function SatelliteComparison() {
  const [sliderPosition, setSliderPosition] = useState(50);
  const [isDragging, setIsDragging] = useState(false);

  const handleMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!isDragging) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 100;
    setSliderPosition(Math.max(0, Math.min(100, x)));
  };

  return (
    <div className="space-y-3">
      <div className="text-xs text-gray-400 uppercase tracking-wide">
        Before/After Satellite Comparison
      </div>
      <div className="text-[10px] text-gray-500">
        Sentinel-2 imagery from Copernicus Programme (EU). Drag slider to compare.
      </div>

      <div
        className="relative w-full h-64 rounded-lg overflow-hidden cursor-col-resize select-none"
        onMouseMove={handleMove}
        onMouseDown={() => setIsDragging(true)}
        onMouseUp={() => setIsDragging(false)}
        onMouseLeave={() => setIsDragging(false)}
      >
        {/* Before image (pre-flood) */}
        <div className="absolute inset-0 bg-gray-800 flex items-center justify-center">
          <div className="text-center">
            <div className="text-2xl mb-2">🛰️</div>
            <div className="text-sm text-gray-300">Pre-Flood</div>
            <div className="text-[10px] text-gray-500">Aug 20, 2026</div>
            <div className="text-[10px] text-gray-600 mt-2">
              Sentinel-2 L2A · Copernicus
            </div>
          </div>
        </div>

        {/* After image (post-flood) - clipped */}
        <div
          className="absolute inset-0 bg-gray-700 flex items-center justify-center"
          style={{ clipPath: `inset(0 0 0 ${sliderPosition}%)` }}
        >
          <div className="text-center">
            <div className="text-2xl mb-2">🌊</div>
            <div className="text-sm text-gray-300">Post-Flood</div>
            <div className="text-[10px] text-gray-500">Aug 28, 2026</div>
            <div className="text-[10px] text-gray-600 mt-2">
              Sentinel-2 L2A · Copernicus
            </div>
          </div>
        </div>

        {/* Slider line */}
        <div
          className="absolute top-0 bottom-0 w-0.5 bg-white shadow-lg"
          style={{ left: `${sliderPosition}%` }}
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 bg-white rounded-full shadow-lg flex items-center justify-center">
            <span className="text-gray-800 text-xs">⇔</span>
          </div>
        </div>
      </div>

      <div className="flex justify-between text-[10px] text-gray-500">
        <span>← Before (Aug 20)</span>
        <span>After (Aug 28) →</span>
      </div>
    </div>
  );
}
