// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — GDACS Alert Proxy Route
// Generated by Hermes Agent (Nous Research)
//
// GET /api/gdacs
// Server-side proxy for GDACS RSS feed — avoids browser CORS issues.
// The browser calls this endpoint instead of gdacs.org directly.
// ─────────────────────────────────────────────────────────────────────────────

import type { NextRequest } from "next/server";

// ── Types ──────────────────────────────────────────────────────────────────────

export interface GDACSAlert {
  alertLevel: "green" | "orange" | "red" | null;
  title: string | null;
  link: string | null;
}

// ── GDACS RSS fetch (server-side, no CORS issues) ─────────────────────────────

const GDACS_RSS_URL = "https://www.gdacs.org/xml/rss.xml";

/**
 * Fetch and parse GDACS RSS feed server-side.
 * Returns the first Nepal-related alert found, or null.
 */
async function fetchGdacsAlert(): Promise<GDACSAlert> {
  try {
    const res = await fetch(GDACS_RSS_URL, {
      signal: AbortSignal.timeout(5000),
      headers: {
        "User-Agent": "NepalFloodMap/1.0 (https://github.com/yrarjun59/nepal-flood-map)",
        Accept: "application/rss+xml",
      },
    });

    if (!res.ok) {
      console.error(`[GDACS] Fetch failed: HTTP ${res.status}`);
      return { alertLevel: null, title: null, link: null };
    }

    const text = await res.text();

    // Find <item> blocks mentioning Nepal / Bhote Koshi / Trishuli
    const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
    const items = [...text.matchAll(itemRegex)].map((m) => m[1]);
    const nepalItem = items.find(
      (i) => /nepal|bhote koshi|lhende|trishuli|rasuwagadhi/i.test(i)
    );

    if (!nepalItem) {
      return { alertLevel: null, title: null, link: null };
    }

    // Extract title (GDACS wraps in CDATA)
    const title =
      nepalItem.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/)?.[1] ??
      nepalItem.match(/<title>(.*?)<\/title>/)?.[1] ??
      null;

    // Extract link
    const link = nepalItem.match(/<link>(.*?)<\/link>/)?.[1] ?? null;

    // Extract alert level from gdacs:alertlevel or severity attribute
    const rawLevel =
      (nepalItem.match(/gdacs:alertlevel>(.*?)</i)?.[1] ??
        nepalItem.match(/<gdacs:alertlevel>(.*?)<\/gdacs:alertlevel>/i)?.[1] ??
        nepalItem.match(/severity="(green|orange|red)"/i)?.[1] ??
        nepalItem.match(/alertlevel.*?["'](green|orange|red)["']/i)?.[1] ??
        ""
      ).toLowerCase();

    const alertLevel =
      rawLevel === "red" ? "red" :
      rawLevel === "orange" ? "orange" :
      rawLevel === "green" ? "green" :
      null; // default to null when no level detected (not a flood event)

    return { alertLevel, title, link };
  } catch (err) {
    console.error(`[GDACS] Error: ${String(err)}`);
    return { alertLevel: null, title: null, link: null };
  }
}

// ── Route Handler ──────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  const alert = await fetchGdacsAlert();
  return Response.json(alert, {
    status: 200,
    headers: {
      "Cache-Control": "public, max-age=60, s-maxage=300", // browser 60s, CDN 5min
    },
  });
}
