// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Vercel cron trigger
// Generated by Hermes Agent (Nous Research)
//
// Fires POST /api/refresh every 10 minutes.
// Add CRON_SECRET to .env.local (openssl rand -hex 32).
// ─────────────────────────────────────────────────────────────────────────────

export const runtime = "nodejs";

export async function GET(request: Request) {
  const auth = request.headers.get("authorization");
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return new Response("Unauthorized", { status: 401 });
  }
  try {
    await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/refresh`, {
      method: "POST",
    });
    return Response.json({
      triggered:   true,
      at:          new Date().toISOString(),
      description: "Nepal flood map data refresh triggered",
    });
  } catch (err) {
    return Response.json({ triggered: false, error: String(err) }, { status: 500 });
  }
}
