// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Agentic Data Source Registry
// Generated by Hermes Agent (Nous Research)
//
// Priority order: govt APIs → UN → scientific → news aggregation → static fallback
// The /api/refresh route works through these in sequence, stopping at first success.
// ─────────────────────────────────────────────────────────────────────────────

export const DATA_SOURCES = {

  // ── TIER 1: Official Nepal Government ──────────────────────────────────────

  BIPAD: {
    name:       "BIPAD — Nepal Disaster Information Management System",
    priority:   1,
    url:        "https://bipadportal.gov.np/",
    apiKey:     undefined,
    updateFreq: "near-real-time during events",
    dataType:   "JSON REST API",
    endpoints: {
      incidents:  "https://bipadportal.gov.np/api/v1/incident/?format=json&page_size=20",
      realtime:   "https://bipadportal.gov.np/api/v1/real-time-monitoring/?format=json",
    },
    notes: "Nepal govt official disaster platform. No auth needed for public read. " +
           "Highest authority for deaths/missing/rescued. Lag: 2-6 hrs after field update.",
  },

  NEPAL_POLICE: {
    name:       "Nepal Police HQ — Official Press Releases",
    priority:   2,
    url:        "https://www.nepalpolice.gov.np/",
    apiKey:     undefined,
    updateFreq: "on-event",
    dataType:   "HTML (scrape)",
    scrapeSelector: ".press-release, .news-item",
    notes: "Primary official source for casualty figures. " +
           "Scrape the press release section for structured announcements.",
  },

  NDRRMA: {
    name:       "National Disaster Risk Reduction and Management Authority",
    priority:   3,
    url:        "https://ndrrma.gov.np/en",
    reportsPath: "/reports",
    apiKey:     undefined,
    updateFreq: "daily during events",
    dataType:   "PDF SITREPs + HTML",
    notes: "Download PDF situation reports from /reports. " +
           "Best for structured overview data, coordination status.",
  },

  // ── TIER 2: UN / International ─────────────────────────────────────────────

  RELIEFWEB: {
    name:       "UN OCHA ReliefWeb API",
    priority:   4,
    url:        "https://reliefweb.int/country/npl",
    apiKey:     undefined, // use appname param — no registration needed
    updateFreq: "hourly",
    dataType:   "JSON REST API",
    endpoints: {
      reports:
        "https://api.reliefweb.int/v1/reports?" +
        "appname=nepal-flood-map&" +
        "filter[conditions][0][field]=country.iso3&" +
        "filter[conditions][0][value]=NPL&" +
        "filter[conditions][1][field]=date.created&" +
        "filter[conditions][1][value][from]=2026-08-26&" +
        "sort[]=date.created:desc&limit=5&" +
        "fields[include][]=title&fields[include][]=date&fields[include][]=body",
    },
    notes: "Aggregates OCHA, UNDP, IFRC SITREPs. " +
           "Best for funding data, coordination updates, downloadable reports.",
  },

  GDACS: {
    name:       "Global Disaster Alert and Coordination System (JRC/UN)",
    priority:   5,
    url:        "https://www.gdacs.org/",
    apiKey:     undefined,
    updateFreq: "every 15 minutes",
    dataType:   "RSS + JSON",
    endpoints: {
      rss:    "https://www.gdacs.org/xml/rss.xml",
      events: "https://www.gdacs.org/gdacsapi/api/events/geteventlist/FLOOD",
    },
    notes: "Critical for secondary event detection — specifically the Tibet barrier lake. " +
           "Will fire orange/red alert if new flood event registered upstream. Poll every 5 min.",
  },

  // ── TIER 3: Scientific / Satellite ─────────────────────────────────────────

  USGS_SEISMIC: {
    name:       "USGS Earthquake Hazards — Landslide / Seismic Monitor",
    priority:   6,
    url:        "https://earthquake.usgs.gov/",
    apiKey:     undefined,
    updateFreq: "real-time",
    dataType:   "GeoJSON",
    endpoints: {
      realtime: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson",
      // Query for Nepal border zone — use for aftershock / secondary trigger monitoring:
      nepal2026:
        "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson" +
        "&starttime=2026-08-26&endtime=2026-09-05" +
        "&minmagnitude=4" +
        "&minlatitude=27&maxlatitude=30&minlongitude=84&maxlongitude=87",
    },
    notes: "Confirmed M5.2 landslide signal at 02:52:10 UTC Aug 26. " +
           "Use for aftershock monitoring and secondary collapse risk.",
  },

  COPERNICUS_EMS: {
    name:       "Copernicus Emergency Management Service (EU Satellite)",
    priority:   7,
    url:        "https://emergency.copernicus.eu/mapping/list-of-components/EMSR",
    apiKey:     undefined,
    updateFreq: "per satellite pass (~12 hr)",
    dataType:   "GeoTIFF + GeoJSON damage polygons",
    notes: "EU activates satellite damage mapping for major disasters. " +
           "Search for Nepal Aug 2026 activation to download before/after GeoJSON extents. Free.",
  },

  DHM_NEPAL: {
    name:       "Department of Hydrology and Meteorology — Nepal",
    priority:   8,
    url:        "http://www.dhm.gov.np/",
    floodForecast: "http://www.dhm.gov.np/floodforecast/",
    apiKey:     undefined,
    updateFreq: "every 3-6 hrs during monsoon",
    dataType:   "HTML table (scrape)",
    notes: "Real river gauge data for Bhote Koshi, Trishuli, Narayani. " +
           "Scrape the flood forecast table for live water levels. Critical right now.",
  },

  NASA_FIRMS: {
    name:       "NASA FIRMS — Near-Real-Time Satellite",
    priority:   9,
    url:        "https://firms.modaps.eosdis.nasa.gov/",
    apiKey:     undefined, // Free registration — set NASA_FIRMS_MAP_KEY in .env.local
    apiKeyEnv:  "NASA_FIRMS_MAP_KEY",
    updateFreq: "daily",
    dataType:   "CSV / GeoJSON",
    endpoint:   "https://firms.modaps.eosdis.nasa.gov/api/area/csv/{MAP_KEY}/VIIRS_SNPP_NRT/world/1",
    notes: "Landslide/flood satellite coverage. Register free at firms.modaps.eosdis.nasa.gov/api/",
  },

  // ── TIER 4: Downstream Risk ────────────────────────────────────────────────

  FFWC_BANGLADESH: {
    name:       "Flood Forecasting Warning Centre — Bangladesh (downstream indicator)",
    priority:   10,
    url:        "http://www.ffwc.gov.bd/",
    apiKey:     undefined,
    updateFreq: "daily",
    dataType:   "HTML",
    notes: "Monitors Gandak/Narayani entering India-Bangladesh. " +
           "Downstream early warning for Bihar/Bengal impact.",
  },

  // ── TIER 5: LLM News Summarization (free alternatives + Gemini primary) ─────

  GEMINI_WEBSEARCH: {
    name:       "Gemini 1.5 Flash — 7 API keys, multi-key fallback",
    priority:   11,
    apiKey:     process.env.GEMINI_API_KEY1,
    apiKeyEnv:  "GEMINI_API_KEY1 through GEMINI_API_KEY7",
    model:      "gemini-1.5-flash",
    tool:       "generateContent (native Gemini API)",
    notes: "Primary LLM for live news aggregation. 7 keys cycled on rate-limit/quota errors. " +
           "1,500 requests/day per key. Searches Nepal Police, AP, Reuters, ABC News, NBC News.",
    // Authoritative news sources to prioritise in the search prompt:
    prioritySources: [
      "https://www.abc.net.au/news/2026-08-28/nepal-tibet-floods-live-updates/107086974",
      "https://www.nbcnews.com/world/asia/live-blog/live-updates-massive-flash-flood-nepal-tibet-border-hundreds-missing-rcna594643",
      "https://www.cbsnews.com/news/nepal-flood-rescue-efforts-death-toll/",
      "https://watchers.news/2026-08-26/bhote-koshi-flash-flood-kills-31-authorities-verify-whereabouts-of-384-travelers-nepal/",
      "https://earthsky.org/earth/nepal-flash-flood-glacier-collapse-landslide-aug-26-2026/",
      "site:apnews.com nepal flood 2026",
      "site:reuters.com nepal bhote koshi 2026",
      "https://english.nepalnews.com/",
      "https://english.onlinekhabar.com/",
    ],
  },

  // ── TIER 6: Static fallback (always works) ─────────────────────────────────

  STATIC_FALLBACK: {
    name:       "Static floodData.ts — verified Aug 29 2026",
    priority:   12,
    apiKey:     undefined,
    notes: "Last resort. Imported from @/data/floodData LIVE_STATS. " +
           "App never crashes — fallback always returns 200.",
  },
} as const;

// Ordered list for the refresh pipeline to iterate
export const SOURCE_PRIORITY_ORDER = [
  "BIPAD",
  "NEPAL_POLICE",
  "NDRRMA",
  "RELIEFWEB",
  "GDACS",
  "USGS_SEISMIC",
  "COPERNICUS_EMS",
  "DHM_NEPAL",
  "NASA_FIRMS",
  "ANTHROPIC_WEBSEARCH",
  "STATIC_FALLBACK",
] as const;
