// ─────────────────────────────────────────────────────────────────────────────
// Nepal Flood Map — Static verified data layer
// Generated by Claude (Anthropic) — claude.ai
//
// Sources:
//   Nepal Police official statements, Aug 26-29 2026
//   ABC News live blog:  https://www.abc.net.au/news/2026-08-28/nepal-tibet-floods-live-updates/107086974
//   NBC News live blog:  https://www.nbcnews.com/world/asia/live-blog/live-updates-massive-flash-flood-nepal-tibet-border-hundreds-missing-rcna594643
//   CBS News:            https://www.cbsnews.com/news/nepal-flood-rescue-efforts-death-toll/
//   The Watchers:        https://watchers.news/2026/08-26/bhote-koshi-flash-flood-kills-31-...
//   EarthSky:            https://earthsky.org/earth/nepal-flash-flood-glacier-collapse-landslide-aug-26-2026/
//   US State Dept (90 Americans missing — Tommy Pigott, Fox News Aug 29)
//   DFAT Australia (38 Australians — confirmed Aug 29)
//   Red Cross (~90,000 impacted — CBS News Aug 28)
//   USGS (M5.2 landslide signal, 02:52:10 UTC Aug 26)
//   ICIMOD (glacier source confirmed via satellite imagery)
// ─────────────────────────────────────────────────────────────────────────────

import type {
  FloodOrigin, FloodLocation, TimelineEvent,
  ActiveAlert, MissingByNationality, LiveStats,
} from "@/types/flood";

export const FLOOD_ORIGIN: FloodOrigin = {
  name: "Glacier Collapse Site — Lhende Khola tributary",
  lat:  28.4000,
  lng:  85.5000,
  time: "08:37 NST (02:52:10 UTC)",
  description:
    "Combined bedrock-and-glacier collapse on the Lhende Khola (Bhote Koshi tributary) " +
    "near the Nepal-Tibet border, ~55 km NW of Kodari. Ice and rock entered the river valley, " +
    "temporarily damming flow before catastrophic release downstream. USGS registered M5.2 " +
    "landslide seismic signal. ICIMOD satellite imagery confirmed glacial source. " +
    "No tectonic earthquake — initial M4.4 report was retracted by USGS. " +
    "Scientists cite climate change as a likely contributing factor.",
  district: "Nepal-Tibet border zone",
  type:     "origin",
};

export const FLOOD_LOCATIONS: FloodLocation[] = [
  {
    id:       1,
    name:     "Rasuwagadhi Border Crossing",
    lat:      28.2776,
    lng:      85.3776,
    time:     "~09:15 NST",
    district: "Rasuwa",
    type:     "border",
    severity: "critical",
    detail:
      "Nepal-China Friendship Bridge destroyed. Gyirong Port (Tibet side) devastated. " +
      "700+ pilgrims and trekkers reported missing at border zone. Satellite before/after " +
      "imagery shows complete clearance of structures. (NBC News / Nepal Police)",
  },
  {
    id:       2,
    name:     "Timure",
    lat:      28.2550,
    lng:      85.3667,
    time:     "~09:30 NST",
    district: "Rasuwa",
    type:     "settlement",
    severity: "critical",
    detail:
      "First major Nepali settlement destroyed by Bhote Koshi surge. " +
      "Homes and roads obliterated. Heavy casualties. Rescue access severely impaired.",
  },
  {
    id:       3,
    name:     "Syapru Besi (Syabrubesi)",
    lat:      28.1637,
    lng:      85.3369,
    time:     "~10:15 NST",
    district: "Rasuwa",
    type:     "settlement",
    severity: "critical",
    detail:
      "Major Langtang trekking circuit hub. Severely flooded. " +
      "Dozens of foreign trekkers reported missing from this area.",
  },
  {
    id:       4,
    name:     "Dhunche",
    lat:      28.1080,
    lng:      85.2981,
    time:     "~10:45 NST",
    district: "Rasuwa",
    type:     "town",
    severity: "high",
    detail:
      "Rasuwa district headquarters. 430 MW hydropower infrastructure damaged — " +
      "~1/8 of Nepal's total generation capacity. Upper Trishuli-1 Hydropower Project " +
      "tunnel contained dozens of trapped workers. (CBS News Aug 28)",
  },
  {
    id:       5,
    name:     "Trishuli Bazar",
    lat:      27.9244,
    lng:      85.1402,
    time:     "~11:30 NST",
    district: "Nuwakot",
    type:     "town",
    severity: "high",
    detail:
      "Trishuli River rose ~9 metres in ~30 minutes. Mudslides compounded flood damage. " +
      "Residents photographed in submerged homes. (AFP/Getty via CBS News)",
  },
  {
    id:       6,
    name:     "Nuwakot District — Mailung / Betrawati",
    lat:      27.9194,
    lng:      85.1661,
    time:     "~11:45 NST",
    district: "Nuwakot",
    type:     "district",
    severity: "high",
    detail:
      "Multiple settlements swept. 19 bridges destroyed across Rasuwa-Nuwakot corridor. " +
      "~40 km of roads washed away. 200+ trucks swept away. (AP / Vision Times Aug 26)",
  },
  {
    id:       7,
    name:     "Devighat",
    lat:      27.8605,
    lng:      85.1103,
    time:     "~13:00 NST",
    district: "Nuwakot/Dhading",
    type:     "junction",
    severity: "medium",
    detail:
      "Trishuli-Narayani river confluence. Bodies recovered here from downstream surge. " +
      "Narayani (Gandak) carries floodwater south into Bihar, India.",
  },
  {
    id:       8,
    name:     "Gorkha / Tanahun / Chitwan — Downstream Zone",
    lat:      27.50,
    lng:      84.85,
    time:     "Afternoon NST+",
    district: "Multiple downstream districts",
    type:     "region",
    severity: "medium",
    detail:
      "Bodies recovered 240+ km from origin. Gandak River surge toward Bihar, India. " +
      "Total affected river corridor ~300 km. ~90,000 people impacted region-wide. " +
      "(Red Cross / CBS News Aug 28)",
  },
];

// GeoJSON coordinate pairs [lng, lat] — Mapbox / GeoJSON standard (lng first)
export const RIVER_FLOW_PATH: [number, number][] = [
  [85.5000, 28.4000], // Glacier collapse origin
  [85.3776, 28.2776], // Rasuwagadhi border
  [85.3667, 28.2550], // Timure
  [85.3369, 28.1637], // Syapru Besi
  [85.2981, 28.1080], // Dhunche
  [85.1402, 27.9244], // Trishuli Bazar
  [85.1661, 27.9194], // Nuwakot
  [85.1103, 27.8605], // Devighat
  [84.85,   27.50  ], // Chitwan / downstream
];

// Static fallback — verified as of ABC News live blog Aug 29 02:42 UTC
// The /api/refresh route will override these with live data
export const LIVE_STATS: LiveStats = {
  deaths_nepal:       579,   // Nepal Police / ABC News Aug 29
  deaths_tibet:         5,   // Chinese state media
  deaths_total:       584,
  missing_nepal:     1900,   // Nepal Police provisional
  missing_foreigners: 700,   // 700+ from 32 countries — NBC News
  missing_americans:   90,   // US State Dept (Tommy Pigott, Aug 29)
  rescued:           3000,   // 3,000+ helicopter-airlifted — CBS News Aug 28
  impacted_total:   90000,   // Red Cross estimate — CBS News Aug 28
  powerloss_mw:       430,   // 13 hydropower projects — AP / Vision Times
  bridges_destroyed:   19,   // AP Aug 26
  roads_destroyed_km:  40,   // AP (~25 miles)
  trucks_swept:       200,   // Vision Times
  countries_affected:  32,   // NBC News
  last_updated:  "2026-08-29T02:42:00Z",
  source:        "Nepal Police / ABC News live blog",
};

export const MISSING_BY_NATIONALITY: MissingByNationality[] = [
  { country: "India",             count: 177, source: "Estimated (pilgrim majority)" },
  { country: "USA",               count:  90, source: "US State Dept confirmed" },
  { country: "Australia",         count:  38, source: "DFAT confirmed Aug 29" },
  { country: "UK",                count:  33, source: "CBS News" },
  { country: "Canada",            count:  25, source: "CBS News" },
  { country: "Other (27 nations)",count: 337, source: "NBC News (700 total foreigners)" },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    time:   "02:52 UTC / 08:37 NST — Aug 26",
    event:  "Glacier collapse",
    detail:
      "Combined bedrock-glacier collapse on Lhende Khola tributary of Bhote Koshi. " +
      "USGS registers M5.2 landslide seismic signal. Initial M4.4 earthquake report " +
      "later retracted. ICIMOD satellite imagery confirms glacial source. " +
      "Scientists cite climate change as likely contributing factor.",
    source: "USGS / ICIMOD / EarthSky",
  },
  {
    time:   "~09:15 NST — Aug 26",
    event:  "Rasuwagadhi border crossing destroyed",
    detail:
      "Temporary dam fails. 9m surge reaches Nepal-China border. " +
      "Friendship Bridge destroyed. Gyirong Port (Tibet side) devastated. " +
      "700+ pilgrims and tourists unaccounted for in border zone.",
    source: "Nepal Police / NBC News",
  },
  {
    time:   "~09:30–10:45 NST — Aug 26",
    event:  "Rasuwa district swept",
    detail:
      "Timure, Syapru Besi, Dhunche obliterated in sequence. " +
      "430 MW hydropower damaged. Dozens of workers trapped in Upper Trishuli-1 tunnel. " +
      "19 bridges and 40 km of roads destroyed.",
    source: "AP / CBS News / Nepal Army",
  },
  {
    time:   "~11:30–13:00 NST — Aug 26",
    event:  "Trishuli–Nuwakot surge",
    detail:
      "Trishuli River rises ~9 metres in ~30 minutes. " +
      "Nuwakot settlements hit: Mailung, Betrawati, Trishuli Bazar. " +
      "Devighat confluence reached. Bodies begin to be recovered.",
    source: "Nepal Police / AFP",
  },
  {
    time:   "Afternoon NST — Aug 26",
    event:  "Downstream spread to Chitwan",
    detail:
      "Surge reaches Gorkha, Tanahun, Chitwan. Bodies recovered 240+ km from source. " +
      "Gandak carries surge toward Bihar, India. ~90,000 people impacted.",
    source: "Red Cross / CBS News",
  },
  {
    time:   "Aug 27",
    event:  "Mass aerial rescue begins",
    detail:
      "Helicopter sorties intensify. 3,000+ airlifted to Kathmandu and Trishuli camp. " +
      "Nepal Army, Nepal Police, Armed Police Force — 14,000+ personnel deployed. " +
      "Army rescues workers from hydropower tunnel in Rasuwa.",
    source: "Nepal Army / CBS News",
  },
  {
    time:   "Aug 28",
    event:  "Toll rises · Secondary lake alert",
    detail:
      "Death toll reaches 579 (Nepal) + 5 (Tibet). Nepal Police issue fresh alert: " +
      "newly formed barrier lake on Tibet side is overflowing. Rescue temporarily suspended. " +
      "Nepal declines foreign SAR teams. ~90,000 impacted (Red Cross).",
    source: "Nepal Police / ABC News / The Watchers",
  },
  {
    time:   "Aug 29 — ONGOING",
    event:  "New flood alert · Search continues",
    detail:
      "Flood Forecasting Division: Bhotekoshi water levels rising again (acting on China data). " +
      "Trishuli River bank residents warned to move immediately. " +
      "38 Australians missing (DFAT). 90 Americans missing (State Dept). " +
      "~1,900 still unaccounted for in Nepal.",
    source: "ABC News / US State Dept / DFAT",
  },
];

export const ACTIVE_ALERTS: ActiveAlert[] = [
  {
    level:       "critical",
    title:       "LIVE — New Flood Alert · Aug 29",
    detail:
      "Nepal Flood Forecasting Division (acting on China data): Bhotekoshi water levels rising. " +
      "All Trishuli River bank residents ordered to safe locations immediately. " +
      "(ABC News Aug 29 02:20 UTC)",
    dismissible: false,
  },
  {
    level:       "critical",
    title:       "Secondary Barrier Lake — Tibet Side",
    detail:
      "Newly formed barrier lake upstream overflowing. Nepal Police fresh alert Aug 28. " +
      "Rescue operations temporarily suspended in high-risk zones.",
    dismissible: false,
  },
  {
    level:       "warning",
    title:       "Monsoon Season Ongoing",
    detail:
      "Continued monsoon rainfall risks secondary landslides along entire 300 km affected stretch. " +
      "13 hydropower projects damaged. Road access to Rasuwa severely limited.",
    dismissible: true,
  },
  {
    level:       "info",
    title:       "Rescue Operations Active",
    detail:
      "3,000+ airlifted as of Aug 28. Nepal declined foreign SAR teams — Nepal Army leading. " +
      "Heavy machinery and search dogs active. Free hospital treatment for all injured.",
    dismissible: true,
  },
];
